1.

In [2]:
import numpy as np

# 1. Crear tres matrices aleatorias A, B y C de 3x3
np.random.seed(42) # Para reproducibilidad de las matrices, usare esto para ejecutar la misma linea de matrices random
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
C = np.random.rand(3, 3)

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)
print("\nMatriz C:\n", C)

# 2. Demostrar las relaciones matriciales

# a) A + B = B + A (Propiedad conmutativa de la suma)
print("Demostrando A + B = B + A:")
print("A + B:\n", A + B)
print("B + A:\n", B + A)
print("¿Son iguales? ", np.allclose(A + B, B + A)) # np.allclose es para comparaciones de punto flotante
print("\n" + "-"*30 + "\n")

# b) A + (B + C) = (A + B) + C (Propiedad asociativa de la suma)
print("Demostrando A + (B + C) = (A + B) + C:")
print("A + (B + C):\n", A + (B + C))
print("(A + B) + C:\n", (A + B) + C)
print("¿Son iguales? ", np.allclose(A + (B + C), (A + B) + C))
print("\n" + "-"*30 + "\n")

# c) k(A + B) = kA + kB (Propiedad distributiva escalar sobre la suma de matrices)
k = 2.5 # Un escalar aleatorio
print("Demostrando k(A + B) = kA + kB (donde k =", k, "):")
print("k * (A + B):\n", k * (A + B))
print("k * A + k * B:\n", k * A + k * B)
print("¿Son iguales? ", np.allclose(k * (A + B), k * A + k * B))
print("\n" + "-"*30 + "\n")

# d) A(BC) = (AB)C (Propiedad asociativa de la multiplicación de matrices)
print("Demostrando A(BC) = (AB)C:")
# Usamos np.dot para la multiplicación de matrices
print("A @ (B @ C):\n", A @ (B @ C)) # @ es el operador de multiplicación de matrices en Python 3.5+
print("(A @ B) @ C:\n", (A @ B) @ C)
print("¿Son iguales? ", np.allclose(A @ (B @ C), (A @ B) @ C))
print("\n" + "-"*30 + "\n")

# e) A(B + C) = AB + AC (Propiedad distributiva de la multiplicación de matrices sobre la suma)
print("Demostrando A(B + C) = AB + AC:")
print("A @ (B + C):\n", A @ (B + C))
print("A @ B + A @ C:\n", A @ B + A @ C)
print("¿Son iguales? ", np.allclose(A @ (B + C), A @ B + A @ C))
print("\n" + "-"*30 + "\n")

# f) (A + B)C = AC + BC (Otra propiedad distributiva)
print("Demostrando (A + B)C = AC + BC:")
print("(A + B) @ C:\n", (A + B) @ C)
print("A @ C + B @ C:\n", A @ C + B @ C)
print("¿Son iguales? ", np.allclose((A + B) @ C, A @ C + B @ C))
print("\n" + "-"*30 + "\n")

# g) (A^T)^T = A (Transpuesta de la transpuesta)
print("Demostrando (A^T)^T = A:")
print("A:\n", A)
print("(A.T).T:\n", (A.T).T)
print("¿Son iguales? ", np.allclose((A.T).T, A))
print("\n" + "-"*30 + "\n")

# h) (A+B)^T = A^T + B^T (Transpuesta de una suma)
print("Demostrando (A+B)^T = A^T + B^T:")
print("(A + B).T:\n", (A + B).T)
print("A.T + B.T:\n", A.T + B.T)
print("¿Son iguales? ", np.allclose((A + B).T, A.T + B.T))
print("\n" + "-"*30 + "\n")

# i) (kA)^T = kA^T (Transpuesta de una multiplicación escalar)
print("Demostrando (kA)^T = kA^T (donde k =", k, "):")
print("(k * A).T:\n", (k * A).T)
print("k * (A.T):\n", k * (A.T))
print("¿Son iguales? ", np.allclose((k * A).T, k * (A.T)))
print("\n" + "-"*30 + "\n")

# j) (AB)^T = B^T A^T (Transpuesta de un producto)
print("Demostrando (AB)^T = B^T A^T:")
print("(A @ B).T:\n", (A @ B).T)
print("B.T @ A.T:\n", B.T @ A.T)
print("¿Son iguales? ", np.allclose((A @ B).T, B.T @ A.T))

Matriz A:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

Matriz B:
 [[0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]

Matriz C:
 [[0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]]
Demostrando A + B = B + A:
A + B:
 [[1.0826127  0.9712988  1.70190379]
 [1.43110112 0.36835775 0.33781949]
 [0.24148812 1.17041839 1.12587144]]
B + A:
 [[1.0826127  0.9712988  1.70190379]
 [1.43110112 0.36835775 0.33781949]
 [0.24148812 1.17041839 1.12587144]]
¿Son iguales?  True

------------------------------

Demostrando A + (B + C) = (A + B) + C:
A + (B + C):
 [[1.51455772 1.26252794 2.31375669]
 [1.57059499 0.6605024  0.70418133]
 [0.69755811 1.95559435 1.32554523]]
(A + B) + C:
 [[1.51455772 1.26252794 2.31375669]
 [1.57059499 0.6605024  0.70418133]
 [0.69755811 1.95559435 1.32554523]]
¿Son iguales?  True

------------------

2.

In [3]:
def determinante(matriz):
    # Paso 1: Caso base - Si la matriz es de 1x1, el determinante es el unico elemento
    if len(matriz) == 1:
        return matriz[0][0]

    # Paso 2: Caso base - Si es 2x2, se usa la formula directa: ad - bc
    if len(matriz) == 2:
        return matriz[0][0]*matriz[1][1] - matriz[0][1]*matriz[1][0]

    # Paso 3: Inicializar el determinante
    det = 0

    # Paso 4: Expandir a lo largo de la primera fila (indice 0)
    for col in range(len(matriz)):
        # Signo alternante: + - + - ...
        signo = (-1) ** col

        # Paso 5: Obtener el menor complementario (submatriz sin fila 0 y columna col)
        submatriz = [fila[:col] + fila[col+1:] for fila in matriz[1:]]

        # Paso 6: Llamada recursiva para el determinante de la submatriz
        det += signo * matriz[0][col] * determinante(submatriz)

    return det


In [ ]:
A = [
    [2, 5, 3],
    [1, -2, -1],
    [1, 3, 4]
]

print("Determinante de A (3x3):", determinante(A))  # → -20

Determinante de A (3x3): -20


In [ ]:
B = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 1, 2, 3],
    [4, 5, 6, 7]
]

print("Determinante de B (4x4):", determinante(B))  # → 0

Determinante de B (4x4): 0


3.

In [6]:
import numpy as np

def gauss_seidel(A, b, tol=1e-7, max_iter=100):
    """
    Metodo de Gauss-Seidel para resolver Ax = b iterativamente.

    Parámetros:
        A (ndarray): Matriz de coeficientes.
        b (ndarray): Vector de términos independientes.
        tol (float): Tolerancia para el criterio de convergencia.
        max_iter (int): Número máximo de iteraciones.

    Retorna:
        x (ndarray): Vector solución aproximado.
        iter_count (int): Número de iteraciones realizadas.
        res_norm (float): Norma del residuo final.
    """
    n = len(b)
    x = np.zeros_like(b, dtype=np.float64)
    iter_count = 0
    convergencia = False

    while iter_count < max_iter and not convergencia:
        x_old = np.copy(x)

        for i in range(n):
            s1 = np.dot(A[i, :i], x[:i])
            s2 = np.dot(A[i, i+1:], x_old[i+1:])
            x[i] = (b[i] - s1 - s2) / A[i, i]

        error = np.linalg.norm(x - x_old, ord=np.inf)
        if error < tol:
            convergencia = True
        else:
            iter_count += 1

    res = b - A @ x
    res_norm = np.linalg.norm(res, ord=np.inf)

    return x, iter_count + 1 if convergencia else iter_count, res_norm

#Generacion del sistema
A = np.random.rand(5, 5)
for i in range(5):
    A[i, i] += 5
b = np.random.rand(5)

#Impresion de las matrices A y b
print("MATRIZ A Y VECTOR b USADOS")
print("Matriz A:")
print(A)
print("\nVector b:")
print(b)

#Solucion con Gauss-Seidel
x_gs, iter_gs, res_norm = gauss_seidel(A, b)

#Soluciones exactas
x_solve = np.linalg.solve(A, b)
x_inv = np.linalg.inv(A) @ b

#Calculo de errores relativos
rel_error_solve = np.linalg.norm(x_gs - x_solve, ord=np.inf) / np.linalg.norm(x_solve, ord=np.inf)
rel_error_inv = np.linalg.norm(x_gs - x_inv, ord=np.inf) / np.linalg.norm(x_inv, ord=np.inf)

#Resultados
print("\nRESULTADOS GAUSS-SEIDEL (PARTE 1)")
print("Solucion Gauss-Seidel:", x_gs)
print("Iteraciones:", iter_gs)
print("Norma del residuo final (inf):", res_norm)

print("\nCOMPARACION Y ERRORES (PARTE 2)")
print("Error relativo vs np.linalg.solve:", rel_error_solve)
print("Error relativo vs inv(A) @ b:", rel_error_inv)


MATRIZ A Y VECTOR b USADOS
Matriz A:
[[5.63755747 0.88721274 0.47221493 0.11959425 0.71324479]
 [0.76078505 5.5612772  0.77096718 0.4937956  0.52273283]
 [0.42754102 0.02541913 5.10789143 0.03142919 0.63641041]
 [0.31435598 0.50857069 0.90756647 5.24929223 0.41038292]
 [0.75555114 0.22879817 0.07697991 0.28975145 5.16122129]]

Vector b:
[0.92969765 0.80812038 0.63340376 0.87146059 0.80367208]

RESULTADOS GAUSS-SEIDEL (PARTE 1)
Solucion Gauss-Seidel: [0.1238383  0.09225115 0.09683125 0.12313654 0.1251382 ]
Iteraciones: 8
Norma del residuo final (inf): 1.574947461335796e-08

COMPARACION Y ERRORES (PARTE 2)
Error relativo vs np.linalg.solve: 2.2709462300549293e-08
Error relativo vs inv(A) @ b: 2.2709462300549293e-08


4.

In [7]:
import numpy as np

def power_method(A, tol=1e-7, max_iter=1000):
    """
    Implementa el metodo de potencias para encontrar el valor y vector propio dominante.

    Args:
        A (np.ndarray): Matriz real cuadrada.
        tol (float): Tolerancia para el criterio de parada.
        max_iter (int): Numero maximo de iteraciones.

    Returns:
        tuple: Una tupla que contiene el valor propio dominante, el vector propio
               normalizado, el numero de iteraciones y la ultima variación relativa
               del valor propio.
    """
    if A.shape[0] != A.shape[1]:
        raise ValueError("La matriz debe ser cuadrada.")

    n = A.shape[0]
    b_k = np.random.rand(n)  # Vector inicial aleatorio
    b_k = b_k / np.linalg.norm(b_k)  # Normalizar

    lambda_k = 0
    num_iter = 0

    for i in range(max_iter):
        num_iter += 1

        # Generar el proximo vector de la sucesion
        b_k1 = A @ b_k

        # Calcular el valor propio estimado
        lambda_k1 = b_k1 @ b_k

        # Normalizar el vector
        b_k1_norm = np.linalg.norm(b_k1)
        b_k = b_k1 / b_k1_norm

        # Calcular la variación relativa
        if lambda_k != 0:
            rel_var = abs((lambda_k1 - lambda_k) / lambda_k)
            if rel_var < tol:
                break

        lambda_k = lambda_k1

    return lambda_k, b_k, num_iter, rel_var if 'rel_var' in locals() else None

#Ejemplo de uso
# Generar una matriz simétrica aleatoria de 6x6
n = 6
random_matrix = np.random.rand(n, n)
A = random_matrix + random_matrix.T

print("Matriz simetrica A:")
print(A)
print("-" * 30)

# Aplicar el método de potencias
lambda_pm, v_pm, iter_pm, rel_var_pm = power_method(A)

print("Resultados del metodo de potencias:")
print(f"Valor propio dominante: {lambda_pm}")
print(f"Vector propio asociado: {v_pm}")
print(f"Número de iteraciones: {iter_pm}")
print(f"Última variación relativa del valor propio: {rel_var_pm}")

# Comparar con numpy.linalg.eig
eigenvalues, eigenvectors = np.linalg.eig(A)

# Encontrar el valor y vector propio dominante de numpy
dom_eigenvalue_np = eigenvalues[np.argmax(np.abs(eigenvalues))]
dom_eigenvector_np = eigenvectors[:, np.argmax(np.abs(eigenvalues))]

# Asegurar que los vectores propios tengan la misma dirección
# (pueden ser opuestos, por lo que se compara el valor absoluto o se normalizan)
if np.sign(dom_eigenvector_np[0]) != np.sign(v_pm[0]):
    dom_eigenvector_np = -dom_eigenvector_np

print("Resultados de numpy.linalg.eig:")
print(f"Valor propio dominante: {dom_eigenvalue_np}")
print(f"Vector propio asociado: {dom_eigenvector_np}")

# Comparacion de resultados
print("Comparacion:")
print(f"Diferencia en el valor propio: {abs(lambda_pm - dom_eigenvalue_np)}")
print(f"Diferencia en el vector propio (norma L2): {np.linalg.norm(v_pm - dom_eigenvector_np)}")

Matriz simetrica A:
[[0.37314012 1.00261092 1.05008954 1.13064309 1.1478736  0.8206825 ]
 [1.00261092 0.45587033 0.84451879 1.33680539 1.35797909 0.05843088]
 [1.05008954 0.84451879 0.44421562 0.82288433 0.63849348 1.22155617]
 [1.13064309 1.33680539 0.82288433 0.7272592  1.25662258 1.87071318]
 [1.1478736  1.35797909 0.63849348 1.25662258 0.07377389 0.84912622]
 [0.8206825  0.05843088 1.22155617 1.87071318 0.84912622 0.28978974]]
------------------------------
Resultados del metodo de potencias:
Valor propio dominante: 5.615935331872148
Vector propio asociado: [0.40152877 0.37681686 0.36447623 0.50752325 0.39237753 0.39038546]
Número de iteraciones: 7
Última variación relativa del valor propio: 6.360595955279591e-08
Resultados de numpy.linalg.eig:
Valor propio dominante: 5.615935737301599
Vector propio asociado: [0.40153008 0.37682946 0.36446859 0.50750881 0.39237244 0.39040296]
Comparacion:
Diferencia en el valor propio: 4.054294509003853e-07
Diferencia en el vector propio (norma L2)

5.

In [8]:
import numpy as np

# Matrices de Pauli y la identidad, dtype=complex para evitar problemas con los j
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I = np.eye(2, dtype=complex)

def generar_hermitiana_aleatoria():
    """
    Genera una matriz hermitiana aleatoria 2x2 con capacidad de usar complejos.
    """
    # Partes reales aleatorias para la diagonal
    a = np.random.uniform(-5, 5)
    d = np.random.uniform(-5, 5)

    # Parte real e imaginaria aleatorias para parte superior
    real = np.random.uniform(-5, 5)
    imag = np.random.uniform(-5, 5)
    b = real + 1j * imag

    # Armar matriz hermitiana
    L = np.array([[a, b], [np.conj(b), d]], dtype=complex)
    return L

def descomponer_hermitiana(L):
    """
    Descompone una matriz hermitiana 2x2 en la base de Pauli + I.
    """
    if not np.allclose(L, L.conj().T):
        raise ValueError("La matriz no es hermitiana.")

    z11 = L[0, 0]
    z22 = L[1, 1]
    z12 = L[0, 1]

    d_coeff = (z11 + z22) / 2
    c_coeff = (z11 - z22) / 2
    a_coeff = np.real(z12)
    b_coeff = -np.imag(z12)

    return a_coeff, b_coeff, c_coeff, d_coeff

#Prueba con varias matrices

n = 3  # Numero de matrices que se generan para la prueba
for i in range(n):
    print(f"\nMATRIZ {i+1}")
    L = generar_hermitiana_aleatoria()
    print("Matriz original hermitiana:\n", L)

    try:
        a, b, c, d = descomponer_hermitiana(L)
        print("Coeficientes:")
        print(f"a = {a:.4f}, b = {b:.4f}, c = {c:.4f}, d = {d:.4f}")

        # Reconstrucción
        L_reconstruida = a * sigma_x + b * sigma_y + c * sigma_z + d * I
        print("Matriz reconstruida:\n", L_reconstruida)

        # Verificación
        if np.allclose(L, L_reconstruida):
            print(" Reconstrucción correcta.")
        else:
            print(" Reconstrucción fallida.")

    except ValueError as e:
        print("Error:", e)


MATRIZ 1
Matriz original hermitiana:
 [[ 2.28216349+0.j          1.32305831+1.33529711j]
 [ 1.32305831-1.33529711j -1.32216867+0.j        ]]
Coeficientes:
a = 1.3231, b = -1.3353, c = 1.8022+0.0000j, d = 0.4800+0.0000j
Matriz reconstruida:
 [[ 2.28216349+0.j          1.32305831+1.33529711j]
 [ 1.32305831-1.33529711j -1.32216867+0.j        ]]
 Reconstrucción correcta.

MATRIZ 2
Matriz original hermitiana:
 [[ 0.35774684+0.j          3.35302496-1.79219935j]
 [ 3.35302496+1.79219935j -4.0971023 +0.j        ]]
Coeficientes:
a = 3.3530, b = 1.7922, c = 2.2274+0.0000j, d = -1.8697+0.0000j
Matriz reconstruida:
 [[ 0.35774684+0.j          3.35302496-1.79219935j]
 [ 3.35302496+1.79219935j -4.0971023 +0.j        ]]
 Reconstrucción correcta.

MATRIZ 3
Matriz original hermitiana:
 [[-3.1348149 +0.j          0.90892943+1.77564362j]
 [ 0.90892943-1.77564362j -4.59224858+0.j        ]]
Coeficientes:
a = 0.9089, b = -1.7756, c = 0.7287+0.0000j, d = -3.8635+0.0000j
Matriz reconstruida:
 [[-3.1348149 +0

6.

Para el uso de numpy.linalg
Matrices comunes ya listas

np.eye(n) crea una matriz identidad de tamaño n × n

np.zeros((n, n)) genera una matriz llena de ceros

np.ones((n, n)) produce una matriz donde todos los elementos son unos

Como construir matrices y vectores

np.array permite definir manualmente vectores o matrices con los valores deseados

np.random.randint(a, b, size=(n, m)) crea una matriz aleatoria de tamaño n × m con enteros entre a y b

Operaciones básicas con matrices

A + B realiza la suma de matrices

A - B permite restarlas

A * B multiplica elemento por elemento (no es multiplicación lineal)

Producto de matrices y vectores

np.matmul(A, B) o A @ B realiza el producto algebraico entre matrices

np.dot(A, b) calcula el producto entre una matriz y un vector

Estas operaciones siguen las reglas tradicionales de álgebra lineal (filas por columnas)

Propiedades importantes

A.T da la transpuesta de la matriz (convierte filas en columnas)

la.det(A) devuelve el determinante de A

la.inv(A) calcula la inversa si A no es singular

np.diagonal(A) extrae la diagonal principal

la.norm(A) mide la norma (longitud) de un vector o matriz

Autovalores y autovectores

valores, vectores = la.eig(A) calcula los valores y vectores propios de la matriz

valores contiene los autovalores

vectores tiene los autovectores correspondientes en columnas

Resolución de sistemas lineales

la.solve(A, b) encuentra la solución del sistema Ax = b si la matriz A tiene inversa

Solo funciona si A es cuadrada y no singular (determinante distinto de cero)

In [9]:
#Ejemplos
import numpy as np
import numpy.linalg as la

# Ejemplo 1: Operaciones basicas entre matrices
A = np.array([[1, 2, 3],
              [0, -1, 4],
              [5, 2, 0]])

B = np.random.randint(0, 10, size=(3, 3))  # matriz aleatoria

C = A + B        # Suma
D = A - B        # Resta
E = A * B        # Multiplicacion elemento a elemento
F = A @ B        # Multiplicacion de matrices

print("Matriz A:\n", A)
print("Matriz B:\n", B)
print("A + B:\n", C)
print("A - B:\n", D)
print("A * B (elemento a elemento):\n", E)
print("A @ B (producto matricial):\n", F)

# Ejemplo 2: Propiedades de una matriz
print("Transpuesta de A:\n", A.T)
print("Determinante de A:", la.det(A))
if not np.isclose(la.det(A), 0):
    print("Inversa de A:\n", la.inv(A))
else:
    print("A no tiene inversa (es singular)")

print("Diagonal de A:", np.diagonal(A))
print("Norma de A:", la.norm(A))

# Ejemplo 3: Autovalores y autovectores
valores, vectores = la.eig(A)
print("Autovalores de A:", valores)
print("Autovectores de A:\n", vectores)

# Ejemplo 4: Resolver un sistema lineal Ax = b
b = np.array([1, 0, -1])
if not np.isclose(la.det(A), 0):
    x = la.solve(A, b)
    print("Solucion de Ax = b:", x)
else:
    print("No se puede resolver el sistema: A es singular")

# Ejemplo 5: Matrices especiales
I = np.eye(3)        # Matriz identidad
Z = np.zeros((3, 3)) # Matriz de ceros
U = np.ones((3, 3))  # Matriz de unos

print("Identidad 3x3:\n", I)
print("Matriz de ceros:\n", Z)
print("Matriz de unos:\n", U)


Matriz A:
 [[ 1  2  3]
 [ 0 -1  4]
 [ 5  2  0]]
Matriz B:
 [[2 9 2]
 [2 3 6]
 [3 8 0]]
A + B:
 [[ 3 11  5]
 [ 2  2 10]
 [ 8 10  0]]
A - B:
 [[-1 -7  1]
 [-2 -4 -2]
 [ 2 -6  0]]
A * B (elemento a elemento):
 [[ 2 18  6]
 [ 0 -3 24]
 [15 16  0]]
A @ B (producto matricial):
 [[15 39 14]
 [10 29 -6]
 [14 51 22]]
Transpuesta de A:
 [[ 1  0  5]
 [ 2 -1  2]
 [ 3  4  0]]
Determinante de A: 46.99999999999999
Inversa de A:
 [[-0.17021277  0.12765957  0.23404255]
 [ 0.42553191 -0.31914894 -0.08510638]
 [ 0.10638298  0.17021277 -0.0212766 ]]
Diagonal de A: [ 1 -1  0]
Norma de A: 7.745966692414834
Autovalores de A: [ 5.68095556+0.j         -2.84047778+0.45270525j -2.84047778-0.45270525j]
Autovectores de A:
 [[ 0.60977158+0.j          0.13272132+0.09447055j  0.13272132-0.09447055j]
 [ 0.40713579+0.j         -0.89161304+0.j         -0.89161304-0.j        ]
 [ 0.68001403+0.j          0.4102485 -0.10090948j  0.4102485 +0.10090948j]]
Solucion de Ax = b: [-0.40425532  0.5106383   0.12765957]
Identidad 3x