In [5]:
#@title Librerias
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

# Parcial III - Métodos Computacionales

### Nombre: Estefania Zapata

---

## ⚠ Importante

👁 Puede usar unicamente las librerias vistas en clase (estas están en la parte superior) en caso de agregar una nueva, debe justificarla.

💀 No está permitido el uso de IA's en caso de hacerlo su parcial será **anulado**!

❗ Comente su código y funciones, esto hace parte de la nota.

✅ Responda ordenadamente y con claridad.


---

# 1

(**35 puntos**) El **método de Jacobi** es un algoritmo iterativo para resolver sistemas lineales de la forma:

$$
A \mathbf{x} = \mathbf{b},
$$

donde \$A\$ es una matriz cuadrada no singular. A diferencia del método de Gauss-Seidel, Jacobi utiliza exclusivamente los valores de la iteración anterior para actualizar todas las variables simultáneamente, lo que lo hace más sencillo de paralelizar pero, en general, con una convergencia más lenta.

## Algoritmo

Dado un sistema lineal \$A \mathbf{x} = \mathbf{b}\$, el método de Jacobi consiste en:

1. Elegir un vector inicial \$\mathbf{x}^{(0)}\$ (por ejemplo, el vector nulo).

2. Para cada iteración \$k\$ y cada componente \$i = 1, 2, ..., n\$, actualizar:

$$
x_i^{(k)} = \frac{1}{a_{ii}} \left( b_i - \sum_{\substack{j=1 \\ j \neq i}}^{n} a_{ij} x_j^{(k-1)} \right)
$$

3. Repetir hasta que se cumpla un criterio de convergencia, como:

$$
\| \mathbf{x}^{(k)} - \mathbf{x}^{(k-1)} \| < \text{tolerancia}
$$

---

**a)** Escriba una función llamada `jacobi` que resuelva el sistema lineal \$A \mathbf{x} = \mathbf{b}\$ usando el método iterativo de Jacobi. La función debe aceptar como argumentos:

* La matriz \$A\$ y el vector \$\mathbf{b}\$,
* Una tolerancia (por defecto \$1\times 10^{-10}\$),
* Un número máximo de iteraciones.

Debe retornar la solución aproximada \$\mathbf{x}\$ y el número de iteraciones realizadas.

---

**b)** Aplique su función para resolver el siguiente sistema de ecuaciones lineales:

$$
\begin{cases}
10x_1 - x_2 + 2x_3 = 6 \\[2mm]
-2x_1 + 11x_2 - x_4 = 25 \\[2mm]
3x_1 - x_2 + 10x_3 - x_4 = -11 \\[2mm]
2x_2 - x_3 + 8x_4 = 15
\end{cases}
$$

Use como vector inicial \$\mathbf{x}^{(0)} = \[0, 0, 0, 0]^T\$. Imprima la solución aproximada y el número de iteraciones necesarias para adquirir la convergencia.

---

**c)** Compare su solución con `np.linalg.solve`. ¿Qué tan cercana es la solución iterativa a la exacta? Para esto, realice un gráfico del error usando la norma euclidiana (`np.linalg.norm`) en función de la tolerancia y otro del número de iteraciones, empleando un `np.logspace(-18, -1, 18)`.

---



In [2]:
def jacobi(A,b, tol = 1e-10, max_iter= 100):
  '''
  Funcion que resuelve el sistema lineal  Ax=b  usando el método iterativo de Jacob
  Entradas:
  A= Matriz
  b= Vector
  tol = tolerancia
  mmax_iter = numero maximo de iteraciones

  Retorna
  x = solucion aproximada del vector x
  iter = numero de iteraciones

  '''
  n = len(A) #dimension de A
  x0 = np.zeros(n) #Vector inicial, vector de ceros del mismo tamaño de A
  iter = 0 #Inicio contador de iteraciones

  for k in max_iter and i,j ...:
    sumatoria = A[i,j] * x0[j]
    xi = (1/[i])*(b[i]- sumatoria) #Operacion para definir xi
    iter +=1 #sumo 1 al contador de iteraciones

    if abs(xi - x0)<tol #evaluacion para la convergencia
      return xi, iter #retorno el valor paroximado de xi y el numero de iteraciones
    else:
      x0 = xi #3 actualizo el valor inicial por el xi calculado





In [11]:
A = (
    [10,-1,2,0],
    [-2,11,0,-1],
    [3,-1,10,-1],
    [0,2,-1,8]
)
b = ([-6, 25,-11,15])
x00 = ([0,0,0,0])
x0 = np.transpose(x00)

In [13]:
sol_linalg = np.linalg.solve(A,b)
print(sol_linalg)

[-0.23072238  2.34035814 -0.67620904  1.20538433]


# 2

(**50 puntos**) El sistema **masa-resorte con fricción** es un modelo clásico en física que describe el movimiento de una masa sujeta a una fuerza restauradora (resorte) y una fuerza disipativa (fricción o viscosidad). Su dinámica está gobernada por la ecuación diferencial de segundo orden:

$$
m y''(t) + c y'(t) + k y(t) = 0,
$$

donde:

* $m$ es la masa del objeto,
* $c$ es el coeficiente de fricción (amortiguamiento),
* $k$ es la constante del resorte,
* $y(t)$ es la posición de la masa respecto a su equilibrio.

---

**a)** Reformule esta ecuación como un sistema de primer orden adecuado para ser resuelto con `solve_ivp`. Explique mediante una función explicita y realice su documentación.

---

**b)** Considere el siguiente caso:

* Masa: $m = 1$ kg
* Constante del resorte: $k = 4$ N/m
* Coeficiente de fricción: $c = 0.5$ N·s/m
* Condiciones iniciales: $y(0) = 1$, $y'(0) = 0$
* Intervalo de tiempo: $t \in [0, 20]$

Utilice `solve_ivp` para resolver el sistema y grafique $y(t)$ como $y'(t)$. Interprete el comportamiento del sistema.

---

**c)** Simule dos escenarios adicionales:

1. Sin fricción: $c = 0$
2. Con fuerte fricción: $c = 4.5$

Grafique los tres casos \$y(t)\$ en una misma figura y compare los regímenes: **no amortiguado**, **subamortiguado**, y **sobreamortiguado**.

---

**d)** Para cada uno de los tres casos, calcule la **energía mecánica total** del sistema en función del tiempo. La energía total se define como la suma de energía cinética y potencial:

$$
E(t) = \frac{1}{2} m v^2 + \frac{1}{2} k y^2
$$

Grafique $E(t)$ para los tres escenarios simulados. Analice y compare el comportamiento de la energía en cada caso. ¿Qué sucede con la energía a lo largo del tiempo? ¿Cómo se relaciona esto con el valor del coeficiente de fricción $c$?


# 3

**(15 puntos)** Sea $A$ una matriz cuadrada de tamaño $n \times n$. Dos propiedades fundamentales de los autovalores de $A$ son:

1. **Determinante**:

   $$
   \det(A) = \prod_{i=1}^{n} \lambda_i
   $$

2. **Traza**:

   $$
   \mathrm{tr}(A) = \sum_{i=1}^{n} \lambda_i
   $$

donde $\lambda_1, \lambda_2, \dots, \lambda_n$ son los autovalores de $A$.

Usando un conjunto de matrices aleatorias $A$ de $5\times 5$ (1000 matrices diferentes), verifique numéricamente ambas propiedades. Puede emplear las funciones `np.linalg.det`, `np.trace` y `np.linalg.eigvals`.


In [51]:
def evaluar_traza(n):
  for i in range(n):
    conteo = 0
    A = np.random.randint(0,10,size=(5,5))
    det_A = la.det(A)
    multiplicatoria = np.prod(eingenvalues_A)
    eingenvalues_A = la.eigvals(A)
    sum = np.sum(eingenvalues_A)
    traza_A = np.trace(A)
    if sum == traza_A and multiplicatoria == det_A
    else: conteo +=1
  return {'No se cumplio la igualdad',conteo, 'veces'}


SyntaxError: invalid syntax (ipython-input-2046858016.py, line 10)

In [49]:
evaluar_traza(1000)

UnboundLocalError: cannot access local variable 'eingenvalues_A' where it is not associated with a value

In [22]:
A = np.random.randint(0,10,size=(5,5))
A

array([[4, 6, 8, 7, 4],
       [8, 5, 5, 9, 4],
       [4, 5, 1, 8, 9],
       [0, 1, 3, 9, 1],
       [6, 7, 2, 6, 2]])

In [28]:
 eingenvalues_A = la.eigvals(A)
 eingenvalues_A

array([22.82313883+0.j        ,  6.63386599+0.j        ,
       -2.61757482+4.12235314j, -2.61757482-4.12235314j,
       -3.22185517+0.j        ])

In [32]:
det_A = la.det(A)
det_A

np.float64(-11632.000000000002)

In [ ]:
multiplicatoria = np.prod(eingenvalues_A)
multiplicatoria

In [34]:
traza_A = np.trace(A)
traza_A

np.int64(21)

In [42]:
sum = np.sum(eingenvalues_A)
sum

np.complex128(21+0j)

np.complex128(-11631.999999999964+0j)