<a href="https://colab.research.google.com/github/jmmarinr/ComputationalMethods/blob/master/Algebra_Lineal/Actividad_08_Algrebra_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: SANTIAGO ANDRES ANGULO TORO 1001154362
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [4]:
import numpy.linalg as la

np.set_printoptions(suppress=True)

rng = np.random.default_rng(42)

A = rng.integers(-5, 6, size=(3,3))
B = rng.integers(-5, 6, size=(3,3))
C = rng.integers(-5, 6, size=(3,3))
c = 3

print("Matrices aleatorias 3x3:\n")
print("A =\n", A)
print("B =\n", B)
print("C =\n", C)
print("Propiedades")

# 1) No conmutatividad
AB = A @ B
BA = B @ A
print("1) AB y BA:")
print("AB =\n", AB)
print("BA =\n", BA)
print("¿AB == BA? ->", np.array_equal(AB, BA))
print()

# 2) Asociatividad
print("2) Asociatividad: (AB)C = A(BC)")
print("||(AB)C - A(BC)||_F =", la.norm((A @ B) @ C - A @ (B @ C)))
print()

# 3) Distributividad derecha
print("3) Distributividad derecha: A(B + C) = AB + AC")
print("||A(B+C) - (AB + AC)||_F =", la.norm(A @ (B + C) - (A @ B + A @ C)))
print()

# 4) Distributividad izquierda
print("4) Distributividad izquierda: (A + B)C = AC + BC")
print("||(A+B)C - (AC + BC)||_F =", la.norm((A + B) @ C - (A @ C + B @ C)))
print()

# 5) Transpuesta del producto
print("5) (AB)^T = B^T A^T")
print("|| (AB)^T - B^T A^T ||_F =", la.norm((A @ B).T - B.T @ A.T))
print()

# 6) Determinante del producto
print("6) Determinante del producto: det(AB) = det(A) det(B)")
print("det(AB) =", la.det(A @ B))
print("det(A)*det(B) =", la.det(A) * la.det(B))
print("Diferencia absoluta =", abs(la.det(A @ B) - la.det(A) * la.det(B)))
print()

# 7) Doble transpuesta
print("7) (A^T)^T = A ->", np.array_equal(A.T.T, A))
print()

# 8) Transpuesta de escalar por matriz
print("8) (cA)^T = c A^T")
print("|| (cA)^T - c A^T ||_F =", la.norm((c * A).T - c * A.T))
print()

# 9) Transpuesta de suma
print("9) (A + B)^T = A^T + B^T")
print("|| (A + B)^T - (A^T + B^T) ||_F =", la.norm((A + B).T - (A.T + B.T)))

Matrices aleatorias 3x3:

A =
 [[-5  3  2]
 [-1 -1  4]
 [-5  2 -3]]
B =
 [[-4  0  5]
 [ 3  3  2]
 [ 3  0 -4]]
C =
 [[ 4 -1  0]
 [-1 -3  5]
 [ 3  2 -1]]
Propiedades
1) AB y BA:
AB =
 [[ 35   9 -27]
 [ 13  -3 -23]
 [ 17   6  -9]]
BA =
 [[ -5  -2 -23]
 [-28  10  12]
 [  5   1  18]]
¿AB == BA? -> False

2) Asociatividad: (AB)C = A(BC)
||(AB)C - A(BC)||_F = 0.0

3) Distributividad derecha: A(B + C) = AB + AC
||A(B+C) - (AB + AC)||_F = 0.0

4) Distributividad izquierda: (A + B)C = AC + BC
||(A+B)C - (AC + BC)||_F = 0.0

5) (AB)^T = B^T A^T
|| (AB)^T - B^T A^T ||_F = 0.0

6) Determinante del producto: det(AB) = det(A) det(B)
det(AB) = -173.99999999999972
det(A)*det(B) = -173.99999999999997
Diferencia absoluta = 2.5579538487363607e-13

7) (A^T)^T = A -> True

8) (cA)^T = c A^T
|| (cA)^T - c A^T ||_F = 0.0

9) (A + B)^T = A^T + B^T
|| (A + B)^T - (A^T + B^T) ||_F = 0.0


#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [6]:
def determinante_laplace(M):
    M = np.array(M, dtype=float)  # asegurar tipo float para evitar errores con enteros
    n = M.shape[0]

    # Caso base: matriz 1x1
    if n == 1:
        return M[0, 0]

    # Caso base: matriz 2x2 (fórmula directa)
    if n == 2:
        return M[0, 0] * M[1, 1] - M[0, 1] * M[1, 0]

    # Expansión por la primera fila
    det = 0
    for j in range(n):
        # Menor M_1j: eliminar fila 0 y columna j
        submatriz = np.delete(np.delete(M, 0, axis=0), j, axis=1)
        # Cofactor
        signo = (-1) ** (1 + (j + 1))
        det += signo * M[0, j] * determinante_laplace(submatriz)

    return det

# Ejemplo de uso
A = np.array([[2, -3, 1],
              [2, 0, -1],
              [1, 4, 5]])

print("Matriz A:\n", A)
print("Determinante calculado con Laplace:", determinante_laplace(A))
print("Determinante con numpy:", np.linalg.det(A))


Matriz A:
 [[ 2 -3  1]
 [ 2  0 -1]
 [ 1  4  5]]
Determinante calculado con Laplace: 49.0
Determinante con numpy: 49.000000000000014


#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [8]:
def gauss_seidel(A, b, tol=1e-7, max_iter=100, x0=None):

    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = A.shape[0]
    if x0 is None:
        x = np.zeros(n, dtype=float)
    else:
        x = np.array(x0, dtype=float)


    for k in range(1, max_iter + 1):
        x_old = x.copy()

        for i in range(n):
            s1 = np.dot(A[i, :i], x[:i])        # usa x^{k+1} ya actualizado
            s2 = np.dot(A[i, i+1:], x_old[i+1:])# usa x^{k}
            x[i] = (b[i] - s1 - s2) / A[i, i]


        if la.norm(x - x_old, ord=np.inf) < tol:
            r = b - A @ x
            return x, k, la.norm(r, ord=np.inf)


    r = b - A @ x                              # si no converge en max_iter, también devuelve el estado alcanzado
    return x, max_iter, la.norm(r, ord=np.inf)

#ejemplo
rng = np.random.default_rng(0)


M = rng.uniform(-1, 1, size=(5, 5))           # Para favorecer la convergencia, hago A diagonalmente dominante.
A = M.copy()
for i in range(5):
    A[i, i] = np.sum(np.abs(M[i])) + 1.0  # estrictamente dominante por filas

b = rng.uniform(-1, 1, size=5)

x_gs, iters, res_inf = gauss_seidel(A, b, tol=1e-7, max_iter=1000)

# “Solución de referencia” con solve
x_ref = la.solve(A, b)

# Comparaciones pedidas
rel_error_vs_solve = la.norm(x_gs - x_ref, ord=np.inf) / la.norm(x_ref, ord=np.inf)

# También con A^{-1} b (solo con fines de comparación numérica)
x_inv = la.inv(A) @ b
rel_error_vs_inv = la.norm(x_gs - x_inv, ord=np.inf) / la.norm(x_inv, ord=np.inf)

# Normas de residuos
res_gs = la.norm(b - A @ x_gs, ord=np.inf)
res_ref = la.norm(b - A @ x_ref, ord=np.inf)
res_inv = la.norm(b - A @ x_inv, ord=np.inf)

print("Iteraciones GS:", iters)
print("residuo GS||_inf:", res_inf)
print("Error relativo vs np.linalg.solve (inf):", rel_error_vs_solve)
print("Error relativo vs inv(A)@b (inf):      ", rel_error_vs_inv)
print("||residuo solve||_inf:", res_ref)
print("||residuo inv||_inf:  ", res_inv)


Iteraciones GS: 9
residuo GS||_inf: 8.520723737692748e-09
Error relativo vs np.linalg.solve (inf): 8.66110953626698e-09
Error relativo vs inv(A)@b (inf):       8.661109522407233e-09
||residuo solve||_inf: 1.1102230246251565e-16
||residuo inv||_inf:   2.220446049250313e-16


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [10]:
def power_method(A, tol=1e-7, max_iter=1000):

    A = np.array(A, dtype=float)
    n = A.shape[0]


    q = np.random.rand(n)    # vector inicial aleatorio normalizado
    q /= la.norm(q, 2)

    lambdaviejo = 0.0

    for k in range(1, max_iter + 1):

        z = A @ q           # multiplicar por A

        q = z / la.norm(z, 2)       # normalizar

        lambdanuevo= q.T @ (A @ q)    # estimar lambda por el cociente de Rayleigh

        rel_var = abs(lambdanuevo - lambdaviejo) / (abs(lambdanuevo) + 1e-15)       # variación relativa
        if rel_var < tol:
            return lambdanuevo, q, k, rel_var
        lambda_old = lambdanuevo

    return lambdanuevo, q, max_iter, rel_var


# Ejemplo
rng = np.random.default_rng(0)

# Matriz simétrica aleatoria 6x6
M = rng.uniform(-1, 1, size=(6, 6))
A = (M + M.T) / 2

lambda_max, v_max, iters, rel_var = power_method(A, tol=1e-7, max_iter=1000)

# Comparación con numpy.linalg.eig
vals, vecs = la.eig(A)
idx_max = np.argmax(np.abs(vals))
lambda_np = vals[idx_max]
v_np = vecs[:, idx_max] / la.norm(vecs[:, idx_max], 2)

print("Matriz A:\n", A)
print("\nResultado método de potencias:")
print("λ_max ≈", lambda_max)
print("v_max ≈", v_max)
print("Iteraciones:", iters, "   Variación relativa final:", rel_var)

print("\nResultado con numpy.linalg.eig:")
print("λ_max numpy =", lambda_np)
print("v_max numpy =", v_np)


Matriz A:
 [[ 0.27392337 -0.12357751 -0.1016222  -0.68376047  0.42865535  0.60120231]
 [-0.12357751  0.45899312 -0.42278943  0.35775964  0.19953111 -0.60834008]
 [-0.1016222  -0.42278943  0.45931089 -0.79602471  0.86038886 -0.32344227]
 [-0.68376047  0.35775964 -0.79602471 -0.75143345  0.65145975  0.36867785]
 [ 0.42865535  0.19953111  0.86038886  0.65145975  0.37108397  0.1758136 ]
 [ 0.60120231 -0.60834008 -0.32344227  0.36867785  0.1758136  -0.37951625]]

Resultado método de potencias:
λ_max ≈ -1.9575763891494424
v_max ≈ [ 0.37039439 -0.04988958  0.35661248  0.73387902 -0.38467869 -0.2158482 ]
Iteraciones: 1000    Variación relativa final: 0.9999999999999994

Resultado con numpy.linalg.eig:
λ_max numpy = -1.9575763891494413
v_max numpy = [ 0.37039439 -0.04988958  0.35661248  0.73387902 -0.38467869 -0.2158482 ]


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [12]:
#Primero hay varias cosas para tener en cuenta

#Definición de matrices de Pauli y la identidad
sigma_x = np.array([[0, 1],
                    [1, 0]], dtype=complex)

sigma_y = np.array([[0, -1j],
                    [1j, 0]], dtype=complex)

sigma_z = np.array([[1, 0],
                    [0, -1]], dtype=complex)

I = np.eye(2, dtype=complex)

#Método 1: Igualación de entradas
def descomponer_igualacion(L):                            #Descompone una matriz hermitiana 2x2 en L = aσx + bσy + cσz + dI usando igualación de entradas.
    alpha = L[0, 0].real
    beta = L[1, 1].real
    gamma = L[0, 1]  # = u - i v

    a = gamma.real  # u
    b = -gamma.imag # v
    c = 0.5 * (alpha - beta)
    d = 0.5 * (alpha + beta)

    return a, b, c, d

#Método 2: Fórmulas con trazas
def descomponer_trazas(L):                                #Descompone usando ortogonalidad con el producto interno tr(A†B).
    a = 0.5 * np.trace(L @ sigma_x).real
    b = 0.5 * np.trace(L @ sigma_y).real
    c = 0.5 * np.trace(L @ sigma_z).real
    d = 0.5 * np.trace(L).real
    return a, b, c, d

#Reconstruye
def reconstruir(a, b, c, d):
    return a*sigma_x + b*sigma_y + c*sigma_z + d*I


In [15]:
# Pauli + identidad
sx = np.array([[0,1],[1,0]], dtype=complex)
sy = np.array([[0,-1j],[1j,0]], dtype=complex)
sz = np.array([[1,0],[0,-1]], dtype=complex)
I  = np.eye(2, dtype=complex)

def descomponer_igualacion1(L):                   # Coeficientes por igualación de entradas
    alpha = L[0,0].real
    beta  = L[1,1].real
    gamma = L[0,1]          # = u - i v
    a = gamma.real
    b = -gamma.imag * (-1)  # b = v  (porque gamma = u - i v)
    c = 0.5*(alpha - beta)
    d = 0.5*(alpha + beta)
    return a, b, c, d

def descomponer_trazas1(L):                     # Coeficientes por fórmulas de traza (Hilbert–Schmid)
    a = 0.5*np.trace(L @ sx).real
    b = 0.5*np.trace(L @ sy).real
    c = 0.5*np.trace(L @ sz).real
    d = 0.5*np.trace(L).real
    return a, b, c, d

def reconstruccion(a,b,c,d):
    return a*sx + b*sy + c*sz + d*I

#Prueba con una hermitiana aleatoria
rng = np.random.default_rng(0)
M = rng.normal(size=(2,2)) + 1j*rng.normal(size=(2,2))
L = 0.5*(M + M.conj().T)   # hermitiana

a1,b1,c1,d1 = descomponer_igualacion1(L)
a2,b2,c2,d2 = descomponer_trazas1(L)

L1 = reconstruccion(a1,b1,c1,d1)
L2 = reconstruccion(a2,b2,c2,d2)

print("||L - L1||_F =", np.linalg.norm(L - L1))
print("||L - L2||_F =", np.linalg.norm(L - L2))
print("(a,b,c,d) por igualación:", (a1,b1,c1,d1))
print("(a,b,c,d) por traza:     ", (a2,b2,c2,d2))


||L - L1||_F = 1.3327619184181307
||L - L2||_F = 0.0
(a,b,c,d) por igualación: (np.float64(0.2541588935759901), np.float64(-0.47120249511032625), np.float64(0.010415051970176795), np.float64(0.1153151691232165))
(a,b,c,d) por traza:      (np.float64(0.2541588935759901), np.float64(0.47120249511032625), np.float64(0.010415051970176795), np.float64(0.1153151691232165))


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

In [22]:

# CREACIÓN DE MATRICES Y VECTORES
# Vector
v = np.array([1, 2, 3])
print("Vector v:\n", v)

# Matriz
M = np.array([[1, 2], [3, 4]])
print("\nMatriz M:\n", M)

# Matriz identidad
I = np.eye(3)
print("\nMatriz identidad I:\n", I)

#OPERACIONES BÁSICAS
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

print("\nA + B:\n", A + B)
print("\nA - B:\n", A - B)
print("\n2 * A:\n", 2 * A)
print("\nA @ B (producto matricial):\n", A @ B)
print("\nTranspuesta de A:\n", A.T)

#DETERMINANTE Y TRAZA
print("\nDeterminante de A:", np.linalg.det(A))
print("Traza de A:", np.trace(A))

# INVERSA Y PSEUDO-INVERSA
print("\nInversa de A:\n", np.linalg.inv(A))

#NORMAS
print("\nNorma euclidiana de v:", np.linalg.norm(v))
print("Norma de Frobenius de A:", np.linalg.norm(A, 'fro'))

#SISTEMAS DE ECUACIONES
A_sistema = np.array([[3, 1], [1, 2]])
b_sistema = np.array([9, 8])

x_sol = np.linalg.solve(A_sistema, b_sistema)
print("\nSolución del sistema de ecuaciones de A_sis y B_sis", x_sol)

#AUTOVALORES Y AUTOVECTORES
eigvals, eigvecs = np.linalg.eig(A)
print("\nAutovalores de A:", eigvals)
print("Autovectores de A:\n", eigvecs)

# DESCOMPOSICIONES IMPORTANTES
U, S, Vh = np.linalg.svd(A)
print("\nDescomposición SVD:")
print("U:\n", U)
print("S (valores singulares):\n", S)
print("Vh:\n", Vh)

#PRODUCTO INTERNO Y ORTOGONALIDAD
print("\nProducto interno complejo (vdot) de v con v:", np.vdot(v, v))
print("Producto escalar real (dot) de v con v:", np.dot(v, v))

#EJEMPLO
A_comb = np.array([[2, 1], [1, 3]])
b_comb = np.array([1, 2])

# Resolver Ax = b
x_comb = np.linalg.solve(A_comb, b_comb)
print("\nEjemplo combinado:")
print("x:", x_comb)
print("Error:", np.linalg.norm(A_comb @ x_comb - b_comb))


Vector v:
 [1 2 3]

Matriz M:
 [[1 2]
 [3 4]]

Matriz identidad I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriz A:
 [[1 2]
 [3 4]]

Matriz B:
 [[5 6]
 [7 8]]

A + B:
 [[ 6  8]
 [10 12]]

A - B:
 [[-4 -4]
 [-4 -4]]

2 * A:
 [[2 4]
 [6 8]]

A @ B (producto matricial):
 [[19 22]
 [43 50]]

Transpuesta de A:
 [[1 3]
 [2 4]]

Determinante de A: -2.0000000000000004
Traza de A: 5

Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Norma euclidiana de v: 3.7416573867739413
Norma de Frobenius de A: 5.477225575051661

Solución del sistema de ecuaciones de A_sis y B_sis [2. 3.]

Autovalores de A: [-0.37228132  5.37228132]
Autovectores de A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Descomposición SVD:
U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S (valores singulares):
 [5.4649857  0.36596619]
Vh:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]

Producto interno complejo (vdot) de v con v: 14
Producto escalar real (dot) de v con v: 14

Ejemplo combinado:
x: [0.2 0.6]
