In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: ______
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [3]:
# Matrices
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

B = np.array([[7, 8, 9],
              [1, 3, 5],
              [2, 4, 6]])

C = np.array([[1, 0, 2],
              [0, 1, 0],
              [3, 0, 1]])

c = 4  # escalar

# 1. AB ≠ BA en general
AB = A @ B
BA = B @ A
print("1. ¿AB = BA?:", np.allclose(AB, BA))
print("AB:\n", AB)
print("BA:\n", BA)

# 2. (AB)C = A(BC)
lhs = (A @ B) @ C
rhs = A @ (B @ C)
print("\n2. ¿(AB)C = A(BC)?:", np.allclose(lhs, rhs))

# 3. A(B + C) = AB + AC
lhs = A @ (B + C)
rhs = A @ B + A @ C
print("\n3. ¿A(B+C) = AB + AC?:", np.allclose(lhs, rhs))

# 4. (A + B)C = AC + BC
lhs = (A + B) @ C
rhs = A @ C + B @ C
print("\n4. ¿(A+B)C = AC + BC?:", np.allclose(lhs, rhs))

# 5. (AB)^T = B^T A^T
lhs = (A @ B).T
rhs = B.T @ A.T
print("\n5. ¿(AB)^T = B^T A^T?:", np.allclose(lhs, rhs))

# 6. det(AB) = det(A) * det(B)
det_AB = np.linalg.det(A @ B)
det_prod = np.linalg.det(A) * np.linalg.det(B)
print("\n6. ¿det(AB) = det(A) * det(B)?:", np.isclose(det_AB, det_prod))

# 7. (A^T)^T = A
print("\n7. ¿(A^T)^T = A?:", np.allclose(A.T.T, A))

# 8. (cA)^T = c A^T
print("\n8. ¿(cA)^T = c A^T?:", np.allclose((c * A).T, c * A.T))

# 9. (A + B)^T = A^T + B^T
print("\n9. ¿(A + B)^T = A^T + B^T?:", np.allclose((A + B).T, A.T + B.T))



1. ¿AB = BA?: False
AB:
 [[15 26 37]
 [ 9 19 29]
 [41 58 75]]
BA:
 [[52 76 53]
 [26 35 15]
 [32 44 22]]

2. ¿(AB)C = A(BC)?: True

3. ¿A(B+C) = AB + AC?: True

4. ¿(A+B)C = AC + BC?: True

5. ¿(AB)^T = B^T A^T?: True

6. ¿det(AB) = det(A) * det(B)?: True

7. ¿(A^T)^T = A?: True

8. ¿(cA)^T = c A^T?: True

9. ¿(A + B)^T = A^T + B^T?: True


#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [5]:
def determinante_laplace(A):
    """
    Calcula el determinante de una matriz cuadrada A usando el Teorema de Laplace (expansión por cofactores).
    El método es recursivo.

    Parámetros:
    - A: matriz cuadrada (numpy.ndarray)

    Retorna:
    - determinante (float)
    """
    n = A.shape[0]  # número de filas (debe ser cuadrada)

    # Caso base 1: matriz de 1x1
    if n == 1:
        return A[0, 0]

    # Caso base 2: matriz de 2x2 (más eficiente calcular directamente)
    if n == 2:
        return A[0, 0]*A[1, 1] - A[0, 1]*A[1, 0]

    # Caso general: expansión por cofactores (primera fila)
    det = 0
    for j in range(n):
        signo = (-1) ** j  # como usamos primera fila, la fórmula es (-1)^(1+j) → j ya parte en 0
        a_1j = A[0, j]  # elemento de la primera fila, columna j

        # Menor M_1j: eliminar fila 0 y columna j
        menor = np.delete(np.delete(A, 0, axis=0), j, axis=1)

        # llamada recursiva
        det += signo * a_1j * determinante_laplace(menor)

    return det

#Ejemplo
A = np.array([[1, 2, 3],
              [0, 4, 5],
              [7, 8, 9]])

print("Determinante (Laplace):", determinante_laplace(A))
print("Determinante (NumPy):", np.linalg.det(A))

Determinante (Laplace): -18
Determinante (NumPy): -17.999999999999996


#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [4]:
def gauss_seidel(A, b, tol=1e-7, max_iter=100):
    """
    Resuelve el sistema Ax = b usando el método de Gauss-Seidel.

    Parámetros:
    - A: matriz cuadrada de tamaño (n, n)
    - b: vector columna de tamaño (n,)
    - tol: tolerancia para el criterio de convergencia
    - max_iter: número máximo de iteraciones permitidas

    Devuelve:
    - x: solución aproximada
    - k: número de iteraciones realizadas
    - residuo: norma infinito del último residuo (Ax - b)
    """
    n = len(b)
    x = np.zeros_like(b, dtype=np.float64)  # vector inicial x^(0)

    for k in range(max_iter):
        x_new = np.copy(x)  # nueva iteración

        for i in range(n):
            # Suma de la parte inferior (usa valores ya actualizados)
            sum_L = np.dot(A[i, :i], x_new[:i])
            # Suma de la parte superior (usa valores de la iteración anterior)
            sum_U = np.dot(A[i, i+1:], x[i+1:])
            # Actualización de x_i^(k+1)
            x_new[i] = (b[i] - sum_L - sum_U) / A[i, i]

        # Norma infinito de la diferencia entre iteraciones sucesivas
        norm_diff = np.linalg.norm(x_new - x, ord=np.inf)

        # Verificamos el criterio de convergencia
        if norm_diff < tol:
            residuo = np.linalg.norm(A @ x_new - b, ord=np.inf)
            return x_new, k + 1, residuo

        x = x_new  # Actualizamos para la siguiente iteración

    # Si no converge:
    residuo = np.linalg.norm(A @ x - b, ord=np.inf)
    return x, max_iter, residuo

# Generar matriz 5x5 y vector b aleatorios
np.random.seed(0)
A = np.random.rand(5, 5) * 10
# Hacemos A estrictamente diagonal dominante (para asegurar convergencia)
for i in range(5):
    A[i, i] += np.sum(np.abs(A[i]))  # diagonal > suma del resto

b = np.random.rand(5) * 10

# Resolver con Gauss-Seidel
x_gs, iters, residuo_gs = gauss_seidel(A, b)

# Solución exacta con NumPy
x_exact = np.linalg.solve(A, b)

# Solución con inversa (menos recomendable pero útil para comparación)
x_inv = np.linalg.inv(A) @ b

# Cálculo de errores relativos
error_rel_solve = np.linalg.norm(x_gs - x_exact, ord=np.inf) / np.linalg.norm(x_exact, ord=np.inf)
error_rel_inv = np.linalg.norm(x_gs - x_inv, ord=np.inf) / np.linalg.norm(x_inv, ord=np.inf)

# Mostrar resultados
print("Solución Gauss-Seidel:", x_gs)
print("Iteraciones:", iters)
print("Residuo final (norma ∞ de Ax - b):", residuo_gs)
print("Error relativo vs. np.linalg.solve:", error_rel_solve)
print("Error relativo vs. A⁻¹b:", error_rel_inv)

Solución Gauss-Seidel: [ 0.14320825 -0.06666852  0.22772673  0.0828462   0.04853291]
Iteraciones: 11
Residuo final (norma ∞ de Ax - b): 5.058993390871791e-07
Error relativo vs. np.linalg.solve: 4.947351627370065e-08
Error relativo vs. A⁻¹b: 4.947351621276012e-08


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [5]:
def power_method(A, tol=1e-7, max_iter=1000):
    """
    Método de potencias para encontrar el valor propio dominante y su vector propio asociado.

    Parámetros:
    - A: matriz cuadrada real (n x n)
    - tol: tolerancia para el cambio relativo en el valor propio
    - max_iter: máximo número de iteraciones

    Devuelve:
    - lambda_max: valor propio dominante
    - v_max: vector propio normalizado correspondiente
    - iteraciones: número de iteraciones realizadas
    - error: última variación relativa en lambda
    """
    n = A.shape[0]
    q = np.random.rand(n)  # vector inicial aleatorio
    q = q / np.linalg.norm(q)  # normalización inicial

    lambda_old = 0

    for k in range(max_iter):
        z = A @ q
        q = z / np.linalg.norm(z)
        lambda_new = q.T @ A @ q  # estimación del valor propio

        # Verificamos convergencia
        if np.abs(lambda_new - lambda_old) < tol * np.abs(lambda_new):
            return lambda_new, q, k + 1, np.abs(lambda_new - lambda_old)

        lambda_old = lambda_new

    # Si no converge
    return lambda_new, q, max_iter, np.abs(lambda_new - lambda_old)

# Generar matriz simétrica aleatoria 6x6
np.random.seed(0)
M = np.random.rand(6, 6)
A = (M + M.T) / 2  # matriz simétrica

# Aplicar método de potencias
lambda_max, v_max, iters, delta = power_method(A)

# Comparar con numpy.linalg.eig
eigvals, eigvecs = np.linalg.eig(A)
idx_max = np.argmax(np.abs(eigvals))
lambda_np = eigvals[idx_max]
v_np = eigvecs[:, idx_max]
v_np_normalized = v_np / np.linalg.norm(v_np)

# Mostrar resultados
print("λ_max (power method):", lambda_max)
print("v_max (power method):", v_max)
print("Iteraciones:", iters)
print("Variación relativa final:", delta)

print("\nλ_max (np.linalg.eig):", lambda_np)
print("v_max (np.linalg.eig normalizado):", v_np_normalized)

λ_max (power method): 3.465978050224171
v_max (power method): [0.37004228 0.51462091 0.36214784 0.46598181 0.30943356 0.39267644]
Iteraciones: 6
Variación relativa final: 3.8499494703359005e-08

λ_max (np.linalg.eig): 3.465978051980294
v_max (np.linalg.eig normalizado): [-0.37004404 -0.51463065 -0.3621312  -0.46598546 -0.30942801 -0.39267742]


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [7]:
# matrices
sigma_x = np.array([[0, 1], [1, 0]])
sigma_y = np.array([[0, -1j], [1j, 0]])
sigma_z = np.array([[1, 0], [0, -1]])
I = np.eye(2)

# Matriz Hermitiana arbitraria
L = np.array([[2, 3 + 1j], [3 - 1j, 4]])

# Coeficientes reales
p, s = L[0, 0].real, L[1, 1].real
q, r = L[0, 1].real, L[0, 1].imag

d = (p + s) / 2
c = (p - s) / 2
a = q
b = r

# Combinación lineal
L_reconstruida = a * sigma_x + b * sigma_y + c * sigma_z + d * I

# Verificación
print("Matriz original:\n", L)
print("\nReconstrucción:\n", L_reconstruida)
print("\n¿Son iguales?:", np.allclose(L, L_reconstruida))

Matriz original:
 [[2.+0.j 3.+1.j]
 [3.-1.j 4.+0.j]]

Reconstrucción:
 [[2.+0.j 3.-1.j]
 [3.+1.j 4.+0.j]]

¿Son iguales?: False


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

In [3]:
'''
a continuación planteare las funciones y métodos más relevantes para algebra lineal usando Python.

Función	                          Descripción
np.dot(A, B)	                    Producto matricial.
np.transpose(A) o A.T	            Transpuesta de una matriz.
np.linalg.inv(A)	                Inversa de una matriz cuadrada.
np.linalg.det(A)	                Determinante de una matriz.
np.linalg.solve(A, b)	            Solución del sistema lineal 𝐴𝑥=𝑏
np.linalg.eig(A)	                Autovalores y autovectores de 𝐴.
np.linalg.norm(x)	                Norma de un vector o matriz.
'''

# ejemplo 1 --> Esto resuelve el sistema de ecuaciones lineales sin invertir explícitamente la matriz.

A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])

x = np.linalg.solve(A, b)
print("Solución del sistema Ax = b:", x)

# ejemplo 2 --> Se verifica que 𝐴⋅𝐴^−1 ≈ 𝐼, la matriz identidad.

A = np.array([[4, 7], [2, 6]])

det_A = np.linalg.det(A)
A_inv = np.linalg.inv(A)
producto = np.dot(A, A_inv)

print("Determinante:", det_A)
print("Inversa de A:\n", A_inv)
print("Verificación A * A_inv:\n", producto)

#ejemplo 3 --> muestra de autovalores y auto vectores

A = np.array([[5, 4], [1, 2]])

valores, vectores = np.linalg.eig(A)

print("Autovalores:", valores)
print("Autovectores:\n", vectores)

Solución del sistema Ax = b: [2.2 3.6]
Determinante: 10.000000000000002
Inversa de A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Verificación A * A_inv:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
Autovalores: [6. 1.]
Autovectores:
 [[ 0.9701425  -0.70710678]
 [ 0.24253563  0.70710678]]
