In [164]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Diego Felipe Diaz Perez
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [165]:
A=np.random.randint(-10,10,(3,3))
B=np.random.randint(-10,10,(3,3))
C=np.random.randint(-10,10,(3,3))
#a
print("AB:",A@B)
print("BA:",B@A)

AB: [[-65  31 -58]
 [ 44  15 -19]
 [-45 -34 -85]]
BA: [[   0 -107  -21]
 [ -48  -86    3]
 [ -16   29  -49]]


In [166]:
#b
print("(AB)C:",(A@B)@C)
print("A(BC):",A@(B@C))

(AB)C: [[ 589  719 -147]
 [-385 -120  -53]
 [ 252 1279 -136]]
A(BC): [[ 589  719 -147]
 [-385 -120  -53]
 [ 252 1279 -136]]


In [167]:
#c
print("A(B+C):",A@(B+C))
print("AB+AC:",A@B+A@C)

A(B+C): [[-74  76 -44]
 [ 12  36 -24]
 [-16  53 -82]]
AB+AC: [[-74  76 -44]
 [ 12  36 -24]
 [-16  53 -82]]


In [168]:
#d
print("(A+B)C:",(A+B)@C)
print("AC+BC:",A@C+B@C)

(A+B)C: [[-50 -84  13]
 [-67 -51  12]
 [128  22  14]]
AC+BC: [[-50 -84  13]
 [-67 -51  12]
 [128  22  14]]


In [169]:
#e
print("(A@B)T:",(A@B).T)
print("BT*AT:",B.T@A.T)

(A@B)T: [[-65  44 -45]
 [ 31  15 -34]
 [-58 -19 -85]]
BT*AT: [[-65  44 -45]
 [ 31  15 -34]
 [-58 -19 -85]]


In [170]:
#f
print("det(AB):",np.linalg.det(A@B))
print("det(A)det(B):",np.linalg.det(A)*np.linalg.det(B))
print(np.isclose(np.linalg.det(A@B),np.linalg.det(A)*np.linalg.det(B)))

det(AB): 314928.0000000002
det(A)det(B): 314928.0000000002
True


In [171]:
#g
print("(AT)T:",(A.T).T)
print("A:",A)

(AT)T: [[ -1 -10   2]
 [  3  -1  -3]
 [ -5  -7  -2]]
A: [[ -1 -10   2]
 [  3  -1  -3]
 [ -5  -7  -2]]


In [172]:
#h
c=np.random.randint(-10,10)
print("(cA)T:",(c*A).T)
print("c*AT:",c*A.T)

(cA)T: [[ 10 -30  50]
 [100  10  70]
 [-20  30  20]]
c*AT: [[ 10 -30  50]
 [100  10  70]
 [-20  30  20]]


In [173]:
#i
print("(A+B)T:",(A+B).T)
print("AT+BT:",A.T+B.T)

(A+B)T: [[  6   7 -14]
 [ -1  -4  -2]
 [  6   4   6]]
AT+BT: [[  6   7 -14]
 [ -1  -4  -2]
 [  6   4   6]]


#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [174]:
def det(A):
  j = A.shape[0] # Use A.shape[0] to get the dimension
  if j == 1:
    return A[0,0]
  d=0
  for k in range(j):
    m = [list(row[:k]) + list(row[k+1:]) for row in A[1:]]#calculamos m
    m = np.array(m)#convertimos la lista en array
    c=((-1)**(1+(k+1)))*A[0][k]*det(m)#calculamos el cofactor
    d+=c#hacemos la sumatoria
  return d #devuelve el determinante

In [175]:
A=np.random.randint(-10,10,(3,3))
print(det(A))
print(np.linalg.det(A))
print(np.isclose(det(A),np.linalg.det(A)))

29
29.000000000000018
True


#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [176]:
def gauss_seidel(A,b,tol=1e-7,max=100):
  # entra una matriz cuadrada A, el vector b, la tolerancia y el maximo de iteraciones
  # sale el vector x aproximado, el numero de iteraciones necesaria y la norma del ultimo residuo
  m,n=A.shape #tomamos las dimenciones de A
  if m!=n: #verificamos que sea cuadrada
    return print("A no es cuadrada")
  if np.linalg.det(A)==0: #verificamos que su determinante sea distinto de 0 para que tenga inversa y el sistema tenga solucion
    return print("determinante 0")
  x=np.zeros(n) # inicializamos x
  for w in range(0,max): #iniciamos el for con la maxima iteraciones que se pidieron
    xn=x.copy() #hacemos una copia de x para comparar en la tolerancia
    for i in range(n):
      sum1=0
      sum2=0 #iniciamos las sumas
      for j in range(n):
        if j<i:
          sum1+=A[i,j]*x[j] #hacemos la primera suma para j<i
        if j>i:
          sum2+=A[i,j]*x[j] #hacemos la segunda suma para j>i
      x[i]=(1/A[i,i])*(b[i]-sum1-sum2) #añadimos xi a x con la formula
    if np.linalg.norm(x-xn)<tol: #verificamos si se cumple la tolerancia
      return x,w,np.linalg.norm(x-xn)
  return print("numero maximo de iteraciones",x) #si se acaba el for significa que se sobrepaso el maximo de itaraciones por lo que mandamos este mensaje

In [195]:
#a
A=np.random.randint(-100,100,(5,5)) #hacemos la matriz A aleatoria
for i in range(5):
  A[i, i] = sum(abs(A[i])) # la funcion no me estaba dando por lo que investigando encontre que gauss_seidel no funciona bien para matrices que no sean diagonalmente dominante por lo que hice este for para asegurar que la diagonal es mas grnde que la fila
b=np.random.randint(-100,100,5)
print(A)
print(b)

[[273  13 -67 -76  21]
 [-71 277  53 -50 -39]
 [-74  35 278  20  77]
 [-64 -88  60 242  -5]
 [-27 -76  85  77 317]]
[-18 -11  19  41  69]


In [196]:
#b
g=gauss_seidel(A,b,1e-7,100000)[0]
s=np.linalg.solve(A,b)
err_s=abs(g-s)
print("error relativo:",err_s)

error relativo: [5.57704125e-09 8.64568949e-09 6.78639536e-09 3.58173149e-09
 2.54745292e-09]


In [197]:
#c
A_inv=np.linalg.inv(A)
x=A_inv@b
err_i=abs(g-x)
print("error relativo:",err_i)

error relativo: [5.57704128e-09 8.64568950e-09 6.78639537e-09 3.58173149e-09
 2.54745292e-09]


In [198]:
print("norma del residuo:",gauss_seidel(A,b,1e-7,100000)[2])
print("error relativo con solve:",err_s)
print("error relativo con el metodo de la inversa:",err_i)

norma del residuo: 4.412954643099395e-08
error relativo con solve: [5.57704125e-09 8.64568949e-09 6.78639536e-09 3.58173149e-09
 2.54745292e-09]
error relativo con el metodo de la inversa: [5.57704128e-09 8.64568950e-09 6.78639537e-09 3.58173149e-09
 2.54745292e-09]


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [180]:
def power_method(A,t=1e-7,max=1000):
  m,n=A.shape
  if m!=n:
    return print("la matriz no es cuadrada")
  q=np.random.randint(-10,10,n)
  ln=0
  for w in range(max):
    nor=np.linalg.norm(A@q)
    q=(A@q)/nor
    l=(q)@A@q
    if abs(l-ln)<t:
      return l,q,w,abs(l-ln)
    else:
      ln=l.copy()
  return print("numero maximo de iteraciones")

In [181]:
#a
m=np.random.randint(-10,10,(6,6))
A=(m+m.T)/2
print(A)

[[ 3.  -1.5  1.5  6.  -4.  -0.5]
 [-1.5 -2.  -2.   1.5  5.  -1. ]
 [ 1.5 -2.  -5.   4.  -0.5 -1.5]
 [ 6.   1.5  4.   7.   5.  -5.5]
 [-4.   5.  -0.5  5.   2.  -7.5]
 [-0.5 -1.  -1.5 -5.5 -7.5 -1. ]]


In [182]:
print(power_method(A))
print(np.linalg.eigvals(A))

(np.float64(16.656347870632015), array([-0.18205561, -0.17686587, -0.14568027, -0.70049189, -0.47332264,
        0.4467978 ]), 19, np.float64(4.377279338996232e-08))
[16.65634789  9.83241483 -1.97183389 -4.19819925 -8.94237824 -7.37635134]


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [183]:
i= 0+1j
x=np.array([[0,1],[1,0]])
y=np.array([[0,-i],[i,0]])
z=np.array([[1,0],[0,-1]])
I=np.array([[1,0],[0,1]])
for i in range(0,100):
  r=np.random.randint(-100,100,4)
  l=r[0]*x+r[1]*y+r[2]*z+r[3]*I
  print(l)

[[ 11. +0.j -60.+61.j]
 [-60.-61.j   1. +0.j]]
[[-108. +0.j   28.-66.j]
 [  28.+66.j    2. +0.j]]
[[ 59. +0.j  66.-63.j]
 [ 66.+63.j -65. +0.j]]
[[-67. +0.j  24.-73.j]
 [ 24.+73.j  71. +0.j]]
[[ 68. +0.j -47.-94.j]
 [-47.+94.j -34. +0.j]]
[[  91. +0.j  -21.+47.j]
 [ -21.-47.j -101. +0.j]]
[[-85. +0.j   2.+61.j]
 [  2.-61.j -95. +0.j]]
[[ -7. +0.j -39.+69.j]
 [-39.-69.j 159. +0.j]]
[[58. +0.j 65.+67.j]
 [65.-67.j 76. +0.j]]
[[-120. +0.j   50.-31.j]
 [  50.+31.j  -56. +0.j]]
[[38. +0.j 59.+67.j]
 [59.-67.j  2. +0.j]]
[[-84. +0.j -99.+14.j]
 [-99.-14.j  32. +0.j]]
[[ 39. +0.j -38.-21.j]
 [-38.+21.j  59. +0.j]]
[[ 52. +0.j -31.+90.j]
 [-31.-90.j  24. +0.j]]
[[157. +0.j -89.-53.j]
 [-89.+53.j  13. +0.j]]
[[  -9.+0.j  -50.-6.j]
 [ -50.+6.j -121.+0.j]]
[[ -58. +0.j   11.+16.j]
 [  11.-16.j -124. +0.j]]
[[-148. +0.j  -75.-77.j]
 [ -75.+77.j   30. +0.j]]
[[ 67. +0.j  45.+90.j]
 [ 45.-90.j -91. +0.j]]
[[110. +0.j -62.-23.j]
 [-62.+23.j  20. +0.j]]
[[-59. +0.j -27.+17.j]
 [-27.-17.j -61. +0.j]]
[

# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

las funciones que se hablaran en este resumen es con la libreria de numpy la cual importaremos como: import numpy as np
# norma
para hacer la norma de una matriz A utilizaremos la funcion np.linalg.norm(A)

In [184]:
#ejemplo
A=np.random.randint(-10,10,(3,3))
norma=np.linalg.norm(A)
print(A)
print(norma)

[[-4  5  0]
 [-9  8 -1]
 [-5  0  1]]
14.594519519326424


# producto de matrices
para hacer el producto dos matrices A y B se utiliza la funcion np.dot(A,B) o A@B

In [185]:
#ejemplo
A=np.random.randint(-10,10,(3,3))
B=np.random.randint(-10,10,(3,3))
p_punto=np.dot(A,B)
p_matriz=A@B
print(A)
print(B)
print(p_punto)
print(p_matriz)

[[  9   2   1]
 [-10   4  -1]
 [  1  -9   4]]
[[ 0 -7  9]
 [ 5  2 -7]
 [ 3  6 -8]]
[[  13  -53   59]
 [  17   72 -110]
 [ -33   -1   40]]
[[  13  -53   59]
 [  17   72 -110]
 [ -33   -1   40]]


# producto cruz
para hacer el producto cruz de dos matrices A y B se utiliza la funcion np.cross(A,B)

In [186]:
#ejemplo
A=np.random.randint(-10,10,(3,3))
B=np.random.randint(-10,10,(3,3))
cruz=np.cross(A,B)
print(A)
print(B)
print(cruz)

[[ 4  2 -1]
 [ 9  5 -7]
 [ 3 -5  2]]
[[ 8 -7 -4]
 [ 2  6  5]
 [ 4  8  4]]
[[-15   8 -44]
 [ 67 -59  44]
 [-36  -4  44]]


# matriz identidad
para generar una matriz identidad de orden n x n se puede hacer con la funcion np.eye(n)

In [187]:
#ejemplo
A=np.eye(5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#matriz aleatoria
para generar una matriz aleatoria en un rango entre a y b con tamaño n x m puedes utilizar la funcion np.random.randint(a,b,size=(m,n))

In [188]:
#ejemplo
A=np.random.randint(-10,10,(3,3))
print(A)

[[  5   2  -6]
 [  8   1   0]
 [-10   6   9]]


# transpuesta
para hacer la traspuesta de una matriz A debes colocar lo siguiente A.T

In [189]:
#ejemplo
A=np.random.randint(-10,10,(3,3))
AT=A.T
print(A)
print(AT)

[[ 9 -7  7]
 [ 9 -8  5]
 [ 8 -9 -9]]
[[ 9  9  8]
 [-7 -8 -9]
 [ 7  5 -9]]


# resolucion de un sistema de ecuaciones
para resolver un sistema de la forma Ax=b hay distintos metodos:
# metodo de la inversa
teniendo Ax=b si obtenemos $A^{-1}$ entonces podemos encontrar x de la forma x=$A^{-1}$b
# descomposicion LU
teniendo Ax=b podemos hacer una sustitucin de A como A=LU donde L es la matriz lower y U la matriz upper y con esto nos queda LUx=b
# metodo de jacobi
el metodo de jacobi es un metodo iterativo para encontrar x por cada indice y su formula es
$$
x_i^{(k+1)} = \frac{1}{A_{ii}} \left( b_i - \sum_{\substack{j = 1 \\ j \ne i}}^{n} A_{ij} x_j^{(k)} \right)
$$
# metodo gauss-seidel
es un metodo mas refinado del de jacobi y su formula es
$$
x_i^{(k+1)} = \frac{1}{A_{ii}} \left( b_i - \sum_{j=1}^{i-1} A_{ij} x_j^{(k+1)} - \sum_{j=i+1}^{n} A_{ij} x_j^{(k)} \right)
$$
# funcion en python
la funcion predilecta para resolver un sistema Ax=b en phyton es np.linalg.solve(A,b)

In [190]:
#ejemplo
A=np.random.randint(-10,10,(3,3))
b=np.random.randint(-10,10,3)
s=np.linalg.solve(A,b)
print(A)
print(b)
print(s)

[[-5  0 -7]
 [ 9  3 -9]
 [ 1  2 -1]]
[-6  1  4]
[0.11111111 2.33333333 0.77777778]


# determinante
para hacer el determinante de una matriz A es con la funcion np.linalg.det(A)

In [191]:
#ejemplo
A=np.random.randint(-10,10,(3,3))
det=np.linalg.det(A)
print(A)
print(det)

[[ -2  -7 -10]
 [ -6  -3   6]
 [ -9   3  -5]]
1044.0000000000005


# inversa
para calcular la inversa de una matriz A se utiliza la funcion np.linalg.inv(A)

In [192]:
#ejemplo
A=np.random.randint(-10,10,(3,3))
inv=np.linalg.inv(A)
print(A)
print(inv)

[[  1   3 -10]
 [  8   7  -3]
 [ -4   7   5]]
[[-0.06451613  0.09792627 -0.0702765 ]
 [ 0.03225806  0.04032258  0.08870968]
 [-0.09677419  0.0218894   0.01958525]]


# traza
para calcular la traza de una matriz A puedes utilizar la funcion np.trace(A)

In [193]:
#ejemplo
A=np.random.randint(-10,10,(3,3))
tra=np.trace(A)
print(A)
print(tra)

[[ 6 -6  1]
 [-1 -6 -9]
 [ 5  5 -1]]
-1
