In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
import numpy as np
from numpy.linalg import det

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Dana Romero Bustos
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [ ]:
np.random.seed(42)
# Generamos las matrices aleatorias A, B y C
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))
C = np.random.randint(1, 10, (3, 3))

print("A =\n", A)
print("B =\n", B)
print("C =\n", C)

A =
 [[7 4 8]
 [5 7 3]
 [7 8 5]]
B =
 [[4 8 8]
 [3 6 5]
 [2 8 6]]
C =
 [[2 5 1]
 [6 9 1]
 [3 7 4]]


In [ ]:
# AB =! BA
AB = A @ B
BA = B @ A
print("AB =\n", AB)
print("BA =\n", BA)
print("AB = BA?", np.allclose(AB, BA))

AB =
 [[ 56 144 124]
 [ 47 106  93]
 [ 62 144 126]]
BA =
 [[124 136  96]
 [ 86  94  67]
 [ 96 112  70]]
AB = BA? False


In [ ]:
# Asociatividad: (𝐴𝐵)𝐶 = 𝐴(𝐵𝐶)

a = (A @ B) @ C
b = A @ (B @ C)
print("¿(AB)C = A(BC)?", np.allclose(a, b))

¿(AB)C = A(BC)? True


In [ ]:
# Distributividad izquierda A(B + C) = AB + AC

a = A @ (B + C)
b = (A @ B) + (A @ C)
print("¿A(B + C) = AB + AC?", np.allclose(a, b))

¿A(B + C) = AB + AC? True


In [ ]:
# Distributividad derecha (A + B)C = AC + BC

a = (A + B) @ C
b = (A @ C) + (B @ C)
print("¿(A + B)C = AC + BC?", np.allclose(a , b))

¿(A + B)C = AC + BC? True


In [ ]:
# Transpuesta del producto

a = (A @ B).T
b = B.T @ A.T
print("¿(AB)^T = B^T A^T?", np.allclose(a , b))

¿(AB)^T = B^T A^T? True


In [ ]:
# Determinante del producto

det1 = np.linalg.det(A @ B)
det2 = np.linalg.det(A) * np.linalg.det(B)
print("¿det(AB) = det(A) * det(B)?", np.isclose(det1, det2))


¿det(AB) = det(A) * det(B)? True


In [ ]:
# Doble Transpuesta

doble_transpuesta = (A.T).T
print("¿(A^T)^T = A?", np.allclose(doble_transpuesta , A))

¿(A^T)^T = A? True


In [ ]:
# (cA)^T = c A^T

c = 15
a = (c * A).T
b = c * (A.T)
print("¿(cA)^T = c A^T?", np.allclose(a , b))

¿(cA)^T = c A^T? True


In [ ]:
# Transpuesta de la suma

sum_transpuesta1 = (A + B).T
sum_transpuesta2 = A.T + B.T
print("¿(A+B)^T = A^T + B^T?", np.allclose(sum_transpuesta1, sum_transpuesta2))


¿(A+B)^T = A^T + B^T? True


#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [ ]:
def laplace(A):
  '''
  Calcula el determinante de una matriz cuadrada A usando
  el Teorema de Laplace de forma recursiva.

  Entradas:
  - A : Array

  Salida:

  - det : float

  '''

  n = A.shape[0]   # Tamaño de la matriz: Como se trabajan con matrices cuadradsa para el calculo del determinante, solo vasta con saber el número de filas o de columnas

  # ---- CASOS BASE ----

  # Si la matriz es 1x1, su determinate es el valor a_11
  if n == 1:
    return A[0 , 0]
  # Si la matriz es 2x2 se realiza el calculo de determinante usual
  elif n == 2:
    return (A[0 , 0] * A[1 , 1]) - (A[0, 1] * A[1, 0])

  # ---- CASO RECURSIVO ----

  det = 0

  for j in range(n):
    # Matriz adjunta: eliminar fila 0 y columna j
    M = np.delete(np.delete(A, 0, axis=0), j, axis=1)

    # Cofactor con el signo (-1)^(1+j)
    cofactor = ((-1)**(j)) * A[0, j] * laplace(M)

    det += cofactor

  return det

#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [ ]:
def gauss_seidel(A, b, tol=1e-7, max_iter=100):
  '''
  Método de Gauss-Seidel para resolver Ax = b.

  Entradas:
  A : array
    Matriz cuadrada de tamaño (n , n)
  b : array
    Vector del lado derecho de tamaño (n , 1).
  tol : float
    Tolerancia para la convergencia
  max_iter : int
    Número máximo de iteraciones

  Salida:
  x : array
    Solución aproximada
  iteraciones : int
    Número de iteraciones
  residuo : float
    Norma del último residuo
  '''

  n = len(b)
  iter = 0
  x = np.zeros_like(b, dtype=float)  # vector inicial

  for k in range(max_iter):
    iter += 1
    x_new = np.copy(x)
    for i in range(n):
      suma1 = np.dot(A[i, :i], x_new[:i])
      suma2 = np.dot(A[i, i+1:], x[i+1:])
      x_new[i] = (b[i] - suma1 - suma2) / A[i, i]

    # Criterio de parada
    if np.linalg.norm(x_new - x, ord=np.inf) < tol:
      break

  x = x_new

  residuo = np.linalg.norm(np.dot(A, x_new) - b, ord=np.inf)

  return x_new, iter, residuo

In [ ]:
# Matriz y vector aleatorios
np.random.seed(42)
A = np.random.rand(5 , 5) * 10

b = np.random.rand(5) * 10

# Gauss-Seidel
x_gauss, iter, residuo = gauss_seidel(A, b)

# Solución con numpy.linalg.solve
x_solve = np.linalg.solve(A, b)

# Solución con x = A^{-1} b
x_inv = np.dot(np.linalg.inv(A), b)

# Errores relativos
error_solve = np.linalg.norm(x_gauss - x_solve) / np.linalg.norm(x_solve)
error_inv = np.linalg.norm(x_gauss - x_inv) / np.linalg.norm(x_inv)

print("Solución Gauss-Seidel:", x_gauss)
print("Iteraciones:", iter)
print("Residuo:", residuo)
print("Error relativo vs solve:", error_solve)
print("Error relativo vs inv:", error_inv)


Solución Gauss-Seidel: [ 2.09637345 -2.19251152  3.12047947 -1.76528677 -2.6208204 ]
Iteraciones: 100
Residuo: 12.659807365334014
Error relativo vs solve: 1.0087069613187132
Error relativo vs inv: 1.0087069613187134


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [ ]:
def power_method(A, tol=1e-7, max_iter=1000):
  '''
  Método de potencias para el valor propio dominante
  Entradas:
  A : array
    Matriz cuadrada real
  tol : float
    Tolerancia para la convergencia
  max_iter : int
    Número máximo de iteraciones.

  Salidas:
  lambda_max : float
    Valor propio dominante.
  v_max : array
    Vector propio asociado a lambda_max
  iteraciones : int
    Número de iteraciones realizadas
  variacion : float
    Última variación relativa de lambda
  '''

  n = A.shape[0]
  q = np.random.rand(n)  # Vector inicial aleatorio
  q = q / np.linalg.norm(q) # Normalizar

  lambda_ant = 0.0

  for k in range(max_iter):
    y = A @ q
    q = y / np.linalg.norm(y) # Normalización
    lambda_nuev = q.T @ A @ q  # Estimación del valor propio

    variacion = abs(lambda_nuev - lambda_ant) / abs(lambda_nuev)
    if variacion < tol:
      return lambda_nuev, q, k+1, variacion

    lambda_ant = lambda_nuev

  return lambda_nuev, q, max_iter, variacion

In [ ]:
# Matriz simétrica aleatoria 6x6
M = np.random.rand(6, 6)
A = (M + M.T) / 2

# Método de potencias
lambda_max, v_max, iters, variacion = power_method(A)

# Resultados con numpy
eig_vals , eig_v = np.linalg.eig(A)
idx = np.argmax(eig_vals)
lambda_np = eig_vals[idx]
v_np = eig_v[:, idx]

print("Método de potencias:")
print("λ_max =", lambda_max)
print("v_max =", v_max)
print("Iteraciones =", iters)
print("Variación final =", variacion)

print("numpy.linalg.eig:")
print("λ_max =", lambda_np)
print("v_max =", v_np)


Método de potencias:
λ_max = 3.0144932901141006
v_max = [0.41952563 0.31258875 0.38448269 0.52930918 0.33646908 0.43020917]
Iteraciones = 7
Variación final = 7.786624974572218e-08
numpy.linalg.eig:
λ_max = 3.0144933119366897
v_max = [0.41951352 0.31263077 0.38443259 0.52933434 0.33644851 0.43022035]


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [ ]:
# Matrices de Pauli y la identidad
sigma_x = np.array([[0, 1],
                    [1, 0]], dtype=complex)

sigma_y = np.array([[0, -1j],
                    [1j, 0]], dtype=complex)

sigma_z = np.array([[1, 0],
                    [0, -1]], dtype=complex)

I = np.eye(2, dtype=complex)

basis = [sigma_x, sigma_y, sigma_z, I]

# Crear matriz hermitiana 2x2
M = np.random.rand(2, 2) + 1j*np.random.rand(2, 2)
L = (M + M.conj().T) / 2  # Hace Hermitiana

# Calculo de coeficientes, tomando en cuenta que  las matrices de Pauli e identidad forman una base ortogonal

coeficientes = [np.trace(L @ B) / 2 for B in basis]
a, b, c, d = coeficientes

# Generamos la matriz L con los coeficientes
L_nuev = a*sigma_x + b*sigma_y + c*sigma_z + d*I

print("¿Las matrices son iguales?", np.allclose(L , L_nuev))

¿Las matrices son iguales? True


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

#  Álgebra Lineal (NumPy)

Mediante la librería **NumPy**, tenemos acceso a funciones que nos permite trabajar con matrices, vectores y operaciones de álgebra lineal.  

## Algunas funciones:

- **Creación de matrices y vectores** → `np.array`
- **Transposición** → `A.T`
- **Producto matricial** → `np.dot(A,B)` o `A @ B`
- **Determinante y traza** → `np.linalg.det(A)`, `np.trace(A)`
- **Inversa y pseudoinversa** → `np.linalg.inv(A)`, `np.linalg.pinv(A)`
- **Resolución de sistemas lineales** → `np.linalg.solve(A,b)`
- **Valores y vectores propios** → `np.linalg.eig(A)`
- **Normas de matrices y vectores** → `np.linalg.norm(A)`
- **Producto punto y cruz** → `np.dot(v1,v2)`, `np.cross(v1,v2)`
- **Comprobaciones útiles** → `np.allclose(A,B)`, `np.isclose(valor,0)`

---

## Ejemplo completo

Resolver un sistema lineal, calcular determinante, inversa, valores y vectores propios:

In [55]:
# Matriz y vector
A = np.array([[4, 2],
              [3, 5]])
b = np.array([10, 13])

# Resolver sistema
x = np.linalg.solve(A, b)

# Determinante, inversa, traza
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
traza_A = np.trace(A)

# Valores y vectores propios
eigvals, eigvecs = np.linalg.eig(A)

# Normas
norma_A = np.linalg.norm(A)

# Producto punto y cruz
product_punto = np.dot([1, 2], [3, 4])
product_cuz = np.cross([1, 0, 0], [0, 1, 0])

# Resultados
print("Solución del sistema x:", x)
print("Determinante:", det_A)
print("Inversa:\n", inv_A)
print("Traza:", traza_A)
print("Valores propios:", eigvals)
print("Vectores propios:\n", eigvecs)
print("Norma de A:", norma_A)
print("Producto punto:", product_punto)
print("Producto cruz:", product_cuz)
print("Verificación A * inv(A) = I:", np.allclose(A @ inv_A, np.eye(2)))

Solución del sistema x: [1.71428571 1.57142857]
Determinante: 14.000000000000004
Inversa:
 [[ 0.35714286 -0.14285714]
 [-0.21428571  0.28571429]]
Traza: 9
Valores propios: [2. 7.]
Vectores propios:
 [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]
Norma de A: 7.3484692283495345
Producto punto: 11
Producto cruz: [0 0 1]
Verificación A * inv(A) = I: True
