In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Mathew stev hernandez marin ti 1089381755
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [ ]:

def Matriz_aleatoria(m,n):
  '''esta funcion genera cualquier matriz aleatorea'''
  matriz = np.random.randint(1, 10, size=(n, m))
  return(matriz)
a= Matriz_aleatoria(3,3)
b= Matriz_aleatoria(3,3)
c= Matriz_aleatoria(3,3)

In [ ]:
a= Matriz_aleatoria(3,3)
b= Matriz_aleatoria(3,3)
c= Matriz_aleatoria(3,3)
#genero 3 matrices aleatorias para probar las hipotesis
# supongo que esto basta para demostrar porque si no tendría que escribir las demostraciones para cada una de las afirmaciones y no sé para que me serviria hacerlo en python
A = np.any(a@b!=b@a)
B = np.any((a@b)@c==a@(b@c))
C = np.any(a@(b+c)==a@b+a@c)
D = np.any((a+b)@c==a@c + b@c)
E = np.any(np.transpose(a@b)==np.transpose(b) @ np.transpose(a))
F = np.any(np.linalg.det(a@b) - (np.linalg.det(a) * np.linalg.det(b)) < 1e-14) # en esta celda si bien a nivel matematico la afirmación es correcta, por el tipo de redondeo del float64 pueden diferir
G = np.any(np.transpose(np.transpose(a))== a)
numero= np.random.randint(1,100000000000000000)# genero un numero random en el espacio mas grande que pueda para la siguiente afirmación
H = np.any(np.transpose(numero*a)==numero*np.transpose(a))
I= np.any(np.transpose(a+b)==np.transpose(a)+np.transpose(b))


In [ ]:
print(f'el valor de verdad de la primera afirmación es {A} ')
print(f'el valor de verdad de la segunda afirmación es {B}')
print(f'el valor de verdad de la tercera afirmacion es {C}')
print(f'el valor de verdad de la cuarta afirmacion es {D}')
print(f'el valor de verdad de la quinta afirmacion es {E}')
print(f'el valor de verdad de la sexta afirmacion es {F}')
print(f'el valor de verdad de la septima afirmacion es {G}')
print(f'el valor de verdad de la octava afirmacion es {H}')
print(f'el valor de verdad de la novena afirmacion es {I}')

el valor de verdad de la primera afirmación es True 
el valor de verdad de la segunda afirmación es True
el valor de verdad de la tercera afirmacion es True
el valor de verdad de la cuarta afirmacion es True
el valor de verdad de la quinta afirmacion es True
el valor de verdad de la sexta afirmacion es True
el valor de verdad de la septima afirmacion es True
el valor de verdad de la octava afirmacion es True
el valor de verdad de la novena afirmacion es True


#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [ ]:
def determinante_laplace(matriz):

  if len(matriz) == 0 or len(matriz[0]) == 0:

    raise ValueError("La matriz está vacía ")

  m= len(matriz[0]) # numero de columnas

  n= len(matriz) # numero de filas

  if n!=m:
    raise ValueError(f'la matriz no es cuadrada')

  if n == 1:
     determinante= matriz[0][0] # si la matriz es de 1x1 el determinante es igual al valor de su unico elemento en el origen
     return determinante
  if n == 2:
    '''esta es la base del funcionamiento de la función dado que es una especie de break
    en la recursividad de la funcion que hace que deje de buscar matrices menores cuando
    encuentre que la matriz menor es de 2x2 dandole el valor de la determinante de esa menor
    que luego servira para comenzar a hacer los calculos de la determinante de la nxn'''

    determinante= (matriz[0][0]*matriz[1][1])-(matriz[0][1]*matriz[1][0]) # esta linea hace que cuando la matriz sea 2x2 calcule la determinante restando las diagonales de la matriz
    return determinante
  '''en caso de matrices nxn mayores a 2x2 inicalizo el determinate en 0'''

  determinante= 0

  for j in range(n): # en el for la j es el indice de la primera fila de  la matriz que se irá recorriendo hasta ser el ultimo de la primera fila

  # defino una matriz sin la primera fila de la matriz que voy a encontrar la determinante
    matriz_sin_fila= np.delete(matriz,0, axis=0) # esta matriz es constante dado que no depende de ningun j del iterador
  # defino una matriz menor
    menor = np.delete(matriz_sin_fila,j, axis=1) # esta matriz borra la columna j-esima de la matriz sin la primera fila
  # defino los cofactores
    cofactores= (-1)**j * matriz[0][j] * determinante_laplace(menor) # esta es la segunda linea clave del codigo, aqui uso la recursividad para encontrar los determinantes de matrices menores mayores a 2x2 hasta que lleguen a ese tamaño
  # ahora realizo la suma de cofacotres para la determinante

    determinante += cofactores

  return determinante


In [ ]:
matriz_prueba = np.array([
    [2,  1,  3,  0,  5],
    [4, -1,  2,  1,  0],
    [0,  3, -2,  4,  1],
    [1,  2,  0, -3,  2],
    [5,  0,  1,  2, -1]
])

print(determinante_laplace(matriz_prueba))
print(np.linalg.det(matriz_prueba))

68
68.00000000000007


In [ ]:
# ahora la pruebo y la comparo con np.linalg.det en una matriz aleatoria
n= np.random.randint(1,10)

matriz_prueba= Matriz_aleatoria(n,n)

print(f'La determinante de la función de laplace es:')
print(determinante_laplace(matriz_prueba))
print(f'La determinante de numpy es:')
print(np.linalg.det(matriz_prueba))
print(f'La diferencia de las determinantes es')
print(abs(determinante_laplace(matriz_prueba)-np.linalg.det(matriz_prueba)))
# después de estar varios minutos ejecutando esta celda el la diferencia mas alta que encontré es de e-8 no es recomendable en matrices mayores a 10x10 el tiempo de respuesta es largo

# algo que me pasó y es que cuando abrí el codigo al siguiente día por ninguna razón en absoluto el codigo no servía y no sé porqué, transcribí el codigo tal cual como estaba y magicamente volvió a funcionar, no tengo ni idea de porque pasó eso

La determinante de la función de laplace es:
-528
La determinante de numpy es:
-528.0
La diferencia de las determinantes es
0.0


#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [434]:
def gauss_seidel(a,b, tol=1e-7, max_iter=100):

  '''Primero doy las condiciones de entrada erroneas para que el código levante un error en caso de que estas pasen

  siendo , que la matriz está vacía, la matriz tiene un solo elemento, la matriz no sea cuadrada o que la matriz no sea de diagonal fuerte, punto que casi me deja calvo porque no entendía porque mi codigo no funcionaba hasta que invetigué y resulta y pasa que el metodo no converge bien alte matrices sin diagonal dominante'''

  if len(a) == 0 or len(a[0]) == 0:

    raise ValueError(f'la matriz está vacía')

  m= len(a[0])

  n= len(a)

  if n== 1:
    raise ValueError(f'la matriz es singular')

  if n!=m:
    raise ValueError(f'la matriz no es cuadrada')

  '''defino las variables para la función'''

  a = np.array(a, dtype=float)

  b = np.array(b, dtype=float)


  x = b*0 # sucede que python me genera un codigo de precaución cuando hago que x sea un array de tamaño nx1 lleno de ceros pero cuando en vez de usar np.zeros(n) o algo asi y simplemente multiplico la matriz a por 0 no me da la advertencia, intenté evitar llegar a una solución tan rustica pero no se me ocurrio nada más

  for k in range(max_iter): # defino k como el numero de iteraciones y lo pongo en un rango de iteraciones hasta max iter



    x_k= x.copy() # hago una copia del vector x que mas bien es una matriz para poder jugar con sus componentes en sin tocar el vector original y poder hacer las iteraciones con x_k y x_k+1 siendo este ultimo el vector x original


    for i in range(n): # comienzo con el for de i hasta n siendo la longitud de a para que vaya indice a indice hasta n
      suma1 = 0 # inicializo las sumas que voy a usar para encontrar cada x[i]

      suma2 = 0

      for j in range(i): # cuando defino el rango así me da que las j van desde 0 hasta i-1 porque python toma el valor anterior, ergo las j menores a i
        suma1 += a[i,j]*x[j] # esta es la expreción de la primera sumatoria que aparece en el ejercicio

    # esto aumenta la sumatoria hasta que se cumpla el for

      for j in range(i+1,n,1): # este rango esta definido diferente dado que aquí empiezo desde el numero despúes de i hasta n la longitud de la matriz a

        suma2 += a[i,j]*x_k[j]


        # estas dos lineas son equivalentes a las de la primera suma

      x[i] = (b[i] - suma1 - suma2) / (a[i][i]) # defino los valores de cada indice de fila de x tal como está en la sumatoria, como ya dije me daba una advertencia que supe solucionar de esta manera, x no es un vector con una sola columna, si no una matriz nxn donde cada columna tiene los valores de la solucion, que se repiten

    residuo= np.linalg.norm(x-x_k) # la norma del resiiduo la defino con np.linalg.norm porque es un array y algo como abs no funciona

    if residuo<tol:
       return x.reshape(-1,1), f'residuo final = {residuo}',f'la ultima iteración= {k+1}' # agrego una condicion que me hace una especie de break cuando la tolerancia minima del residuo se cumple, por lo tanto puedo afirmar que ya convergió por asi decirlo

       '''dada la naturaleza array del x solo tomo su primera columna como respuesta y la reordeno para que me quede de la misma forma que np.linalg.solve'''

  raise ValueError(f'no se llegó a una convergencia en las iteraciones planteadas') # en caso de que durante el for de k se llegué al maximo de iteraciones y no se cumpla la condición de pseudo-break significa que no convergió en nuestro maximo de iteraciones, por lo que la función falló

In [435]:
def matriz_diagonal_dominante(n): # dado que la función no converge en matrices sin diagonal dominante creo un codigo que me genere una matriz al azar con diagonal dominante

    A = np.random.rand(n, n) # genero una matriz cualquiera cuadrada y aleatoria

    for i in range(n):

        suma_fila = np.sum(np.abs(A[i, :])) - np.abs(A[i, i]) # utilizo esta suma para obtener el valor de la suma que hay alrededor del valor respectivo de la diagonal sin tener en cuenta el valor del punto en la diagonal, por eso lo resto

        A[i, i] = suma_fila + np.random.rand()  #  luego redefino el valor del numero en la diagonal como un numero random mas la suma de la fila, para que si o si sea mayor

    return A
matriz5x5= matriz_diagonal_dominante(5)
matriz_b = Matriz_aleatoria(1,5)
soluciones,residuo,iteracion=gauss_seidel(matriz5x5,matriz_b)
con_linalg= np.linalg.solve(matriz5x5,matriz_b)
con_la_inversa= np.linalg.inv(matriz5x5)@matriz_b
print(f'Funcionamiento de la función gauss_sidel')
display(gauss_seidel(matriz5x5,matriz_b))
print(f'El valor de las respuestas de np.linalg.solve es:')
print(con_linalg)
print(f'El valor de las respuestas de la funcion gauss_sidel es:')
print(soluciones)
print(f'El valor de las respuestas de la inversa es:')
print(con_la_inversa)
print(f'El error respecto a np.linalg.solve es:')
print(con_linalg-soluciones)
print(f'El error respecto a la inversa es:')
print(con_la_inversa-soluciones)
print(f'La norma del residuo es:')
print(residuo)

Funcionamiento de la función gauss_sidel


(array([[ 0.00873965],
        [ 2.46996758],
        [ 5.29211706],
        [-1.72309764],
        [ 1.56440724]]),
 'residuo final = 7.386531812390272e-08',
 'la ultima iteración= 14')

El valor de las respuestas de np.linalg.solve es:
[[ 0.00873966]
 [ 2.46996758]
 [ 5.29211705]
 [-1.72309765]
 [ 1.56440723]]
El valor de las respuestas de la funcion gauss_sidel es:
[[ 0.00873965]
 [ 2.46996758]
 [ 5.29211706]
 [-1.72309764]
 [ 1.56440724]]
El valor de las respuestas de la inversa es:
[[ 0.00873966]
 [ 2.46996758]
 [ 5.29211705]
 [-1.72309765]
 [ 1.56440723]]
El error respecto a np.linalg.solve es:
[[ 7.21216720e-09]
 [ 7.93949795e-10]
 [-1.83983317e-09]
 [-7.40864881e-09]
 [-2.45167553e-09]]
El error respecto a la inversa es:
[[ 7.21216718e-09]
 [ 7.93950239e-10]
 [-1.83983317e-09]
 [-7.40864903e-09]
 [-2.45167575e-09]]
La norma del residuo es:
residuo final = 7.386531812390272e-08


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [492]:
def power_method(a,tol=1e-17,max_iter=1000): # hice el codigo de manera basica copiando la estructura de una suceción de fibonacci basica
  #defino el vector inicial distinto de 0
  q_k = np.array([1 for i in range(len(a))]).reshape(-1,1)
  λ_k1= 0
  itera= 0
  # defino λ_k1 e itera para inicializarlos en 0 y que luego puedan ser reemplazados sin que salte un error de no definición
  for k in range(max_iter):
    q_k1= a@q_k/np.linalg.norm(a@q_k) # defino q_k1 y q_k2 en función de la suceción para poder trabajar con reemplazos en lineas siguientes

    q_k2= a@q_k1/np.linalg.norm(a@q_k1)

    λ_k2= np.transpose(q_k1)@a@q_k1 # igualmente defino λ_k2 en función de la sucesión

    variación= abs(λ_k2-λ_k1) # calculo la variación de los lambdas con el λ_k2 y el λ_k1 inicializado en 0 para luego reemplazarlo por λ_k2

    q_k1= q_k2 # reemplazo a q_k1 como q_k2 para poder volver con el proceso de iteración con el proceso sustituido dado que q_k2 está en función de q_k1 todo sigue en forma de suceción

    λ_k1 = λ_k2

    itera += 1
    if variación < tol:
       return λ_k2, q_k2,itera, variación # la verdad no sé exactamente porque q_k2 es el vector asociado al valor máximo, porque si la suceción converge a vmax/∥vmax∥2 vmax debería ser igual a q_k2*∥vmax∥2 pero este vector no se corresponde a lo que debería, pero funciona
  raise ValueError(f'no se llegó a una convergencia en el numero maximo de iteraciones')
  # Dios bendiga a la patria porque despues de matarme la cabeza con los 2 anteriores esto fue un regalito del cielo

In [499]:
def Matriz_simetrica_aleatorea(n):
  M = np.random.randint(1, 10, size=(n, n))
  Mt= np.transpose(M)
  return (M+Mt)/2 # una función para crear una matriz como la pide el ejercicio
Matriz_simetrica= Matriz_simetrica_aleatorea(6)
print(f'la matriz aleatorea fue')
print("")
print(Matriz_simetrica)
lambdas,Vmax,iteraciones,variaciones= power_method(Matriz_simetrica)
linalg_valores,linalg_Vectores=np.linalg.eig(Matriz_simetrica)
print("")
print(f'los valores que retorna mi función')
print(f'el valor maximo es {lambdas},el vector maximo es {Vmax},el numero de iteraciones fueron {iteraciones},la ultima variación en los lambdas fue {variaciones}')
print("")
print(f'el valor maximo de la función es:')
print(lambdas)
print("")
print(f'el vector maximo de la función es:')
print(Vmax)
print("")
print(f'el valor maximo con linalg es:')
print(max(linalg_valores))
print("")
print(f'el vector maximo con linalg es:')
print((linalg_Vectores[:,0]).reshape(-1,1)) # nada mas me importa el primer vector dado que linalg.eig me devuelve cada valor en la posicion de su vector correspondiente y los valores dominantes están en la primera columna

# converge muy rápido, pero prestando atención, se alcanza a ver que difiere despues del tercer decimal por mas que se baje la tolerancia

la matriz aleatorea fue

[[6.  5.  7.  6.5 7.5 5. ]
 [5.  3.  7.5 7.  3.  5. ]
 [7.  7.5 7.  6.  3.  8.5]
 [6.5 7.  6.  2.  3.5 8.5]
 [7.5 3.  3.  3.5 8.  4.5]
 [5.  5.  8.5 8.5 4.5 4. ]]

los valores que retorna mi función
el valor maximo es [[34.50558462]],el vector maximo es [[0.43554515]
 [0.36852495]
 [0.46586791]
 [0.39970915]
 [0.34423228]
 [0.42331267]],el numero de iteraciones fueron 2,la ultima variación en los lambdas fue [[0.]]

el valor maximo de la función es:
[[34.50558462]]

el vector maximo de la función es:
[[0.43554515]
 [0.36852495]
 [0.46586791]
 [0.39970915]
 [0.34423228]
 [0.42331267]]

el valor maximo con linalg es:
34.50987732331558

el vector maximo con linalg es:
[[-0.43491372]
 [-0.36885114]
 [-0.4667715 ]
 [-0.40017678]
 [-0.34237102]
 [-0.4237498 ]]


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [523]:
# si la matriz hermitiana siempre se puede escribir de la forma L= aσx + bσy + cσz + dI eso significa que sin importar la matriz hermitiana siempre habrá una solución al sistema de ecuaciones de a,b,c y d que multiplicados por la identidad y pauli den la matriz L
# si genero una matriz de hermit aleateorea siempre habrá a,b,c y d tales que la ecuación se satisfaga
def solucion_hermit(l):
  n= len(l)
  if n!=2:
    raise ValueError(f'la matriz no es 2x2')
  # defino la matriz identidad y las de pauli de modo que todas sean complejas
  pauli1 = np.array([[0, 1], [1, 0]], dtype=complex)
  pauli2 = np.array([[0, -1j], [1j, 0]], dtype=complex)
  pauli3 = np.array([[1, 0], [0, -1]], dtype=complex)
  identidad = np.eye(2, dtype=complex)
  # ahora se definen los valores de las partes reales e imaginarias para poder hacer un sistema de ecuaciones que me defina las componentes a,b,c y d en función de las componentes alpha,betha,x y y
  alpha = l[0, 0].real
  betha = l[1, 1].real
  x = l[1, 0].real
  y = l[1, 0].imag
  ''' (c+d , a+ib)
      (a−ib,−c+d)
      es la forma de las matrices de pauli por las constantes abc mas la matriz identidad multiplicada por d
      si la matriz hermitiana es igual a la de pauli con la identidad  sus comoponentes son iguales entonces lo igualo a la forma general de la matriz hermitiana
      ( alpha, x + iy)
      ​(x - iy,   betha )
       así que se debe plantear el sistema de ecuaciones
       obtengo componente a componente que:
       c+d = alpha
       a+ib = x − iy entonces a=x, y=b
       −c+d = betha
       resolviendo y definiendo ya para el código
       '''
  a = x
  b = y
  c = (alpha-betha)/2
  d = (alpha+betha)/2

  suma_matrices= a*pauli1 + b*pauli2 + c*pauli3 + d*identidad
  return a,b,c,d, suma_matrices
def matriz_hermitiana_aleatoria():# genero una funcion sin entradas dado que todo en ella es aleatoreo y no necesito especificar su tamaño
  # genero 4 numeros aleatoreos al azar
    a = np.random.rand()
    b = np.random.rand()
    x = np.random.rand()
    y = np.random.rand()
    z = x + 1j*y # defino z como un numero complejo con coponente real x y componente imaginaria y
    H = np.array([[a, z],
                  [np.conj(z), b]], dtype=complex) #defino una matriz H con componentes a,z,zconjugado,b

    return H # me devuelve H
L= matriz_hermitiana_aleatoria()
a,b,c,d,suma= solucion_hermit(L)
print(f'la matriz hermitiana es:')
print(L)
print("")
print(f'las constantes son:')
print(f'a={a}, b={b}, c={c}, d={d}')
print("")
print(f'la suma de las matrices de pauli es:')
print(suma)

#sin importar la matriz hermitiana siempre tiene solución

la matriz hermitiana es:
[[0.33040009+0.j        0.37024666+0.0643144j]
 [0.37024666-0.0643144j 0.93441699+0.j       ]]

las constantes son:
a=0.37024666406115125, b=-0.06431440109946396, c=-0.30200845080992444, d=0.6324085372410725

la suma de las matrices de pauli es:
[[0.33040009+0.j        0.37024666+0.0643144j]
 [0.37024666-0.0643144j 0.93441699+0.j       ]]


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

In [525]:
'''definitivamente las funciones mas básicas como en todo son las mas importantes y relevantes dado que en base a estas es que se construyen todas las demás y pueden funcionar los metodos, entre las que fueron mas relevantes para mí son aquellas que realizan las operaciones
de matrices como "@" para realizar el producto punto de dos vectores np.transpose para realizar la transpuesta, np.linalg.inv para realizar la inversa de una matriz y poder resolver sistemas de ecuaciones lineales, np.linalg.det para poder calcular la determinante de una matriz
que en muchos metodos numericos y en gran numero de operaciones dentro del algebra lineal, una que no sé si cuente como función sería todo lo que se puede hacer con A[][] con este comando se puede acceder a puntos especificos de una matriz o seccionarla comando que facilita todo en gran medida
, de los metodos vistos en la actividad mencionaría el punto 2 y 2 el punto 3 tanto por lo bien que convergen como por su utilidad fundamental en los dos conceptos mas básicos e importantes del algebra, las determinantes y las soluciones de sistemas '''

'definitivamente las funciones mas básicas como en todo son las mas importantes y relevantes dado que en base a estas es que se construyen todas las demás y pueden funcionar los metodos, entre las que fueron mas relevantes para mí son aquellas que realizan las operaciones \nde matrices como "@" para realizar el producto punto de dos vectores np.transpose para realizar la transpuesta, np.linalg.inv para realizar la inversa de una matriz y poder resolver sistemas de ecuaciones lineales, np.linalg.det para poder calcular la determinante de una matriz\nque en muchos metodos numericos y en gran numero de operaciones dentro del algebra lineal, una que no sé si cuente como función sería todo lo que se puede hacer con A[][] con este comando se puede acceder a puntos especificos de una matriz o seccionarla comando que facilita todo en gran medida\n, de los metodos vistos en la actividad mencionaría el punto 2 y 2 el punto 3 tanto por lo bien que convergen como por su utilidad fundamental en los

In [ ]:
n=np.ranom.randint(1,10)
a= Matriz_aleatoria(n)
b= Matriz_aleatoria(n)
'''ejemplos'''
#producto punto
print(b@a)
# determinante
print(np.linalg.det(b))
# transpuesta
print(np.transpose(a))
# inversa
print(np.linalg.inv(b))
'''funciones igual de básicas como importantes facilitando cualquier operación o codigo de manera comoda y rapida aparte de poder optimizar todo mucho mas rapido'''